const en = {
    metaTitle: 'Install LUTA safely',
    brand: 'LUTA',
    pageTitle: 'Install LUTA',
    pageDescription: 'Choose the installation method that works best for you.',
    openInstalledApp: 'Already installed LUTA? Open the App',
    loadingTitle: 'Preparing installation options',
    loadingDescription: 'We are checking the currently available official channels.',
    retry: 'Try again',
    choiceLegend: 'Which region works for you?',
    choiceHint: 'This only changes the order of the options. You can still switch to every available method below.',
    choiceHelpTitle: 'Not sure which one to choose?',
    choiceHelpDescription: 'Search for “LUTA” in the App Store. If you can find it, choose “Mainland China”; if you cannot, choose “Other countries or regions”.',
    regionCnTitle: 'Mainland China',
    regionCnDescription: 'Continue to the App Store',
    regionGlobalTitle: 'Other countries or regions',
    regionGlobalDescription: 'View the installation methods currently available to you',
    recommended: 'Suggested first',
    otherOptions: 'Available installation methods',
    androidOptionsTitle: 'Choose how you usually download mobile apps',
    allOptionsHint: 'The campaign source only affects ordering and never hides another available channel.',
    noCompatibleChoiceTitle: 'This choice is not available on your device right now',
    noCompatibleChoiceDescription: 'We will not send you to a store for another device or to an unavailable region. Choose another method below or return to the LUTA website.',
    channelAppleCn: 'App Store · Mainland China',
    channelAppleGlobal: 'App Store · Other regions',
    channelGooglePlay: 'Google Play',
    channelApk: 'Official Android package',
    channelOtherStore: 'Other verified app store',
    channelTestFlight: 'iPhone beta',
    channelWaitlist: 'Notify me when available',
    channelWeb: 'Continue on the LUTA website',
    channelUnknown: 'Other official option',
    regionCnBadge: 'Mainland China',
    regionGlobalBadge: 'Other regions',
    regionUnknownBadge: 'Region independent',
    statusAvailable: 'Available',
    statusUnavailable: 'Not available yet',
    statusUnverified: 'Information pending verification',
    continueAction: 'Continue',
    unavailableAction: 'Choose another method',
    optionDefaultDescription: 'We will confirm availability before opening the official destination.',
    mismatchHint: 'This option is different from your preference, but you can still use it if it is available to you.',
    mismatchAction: 'Use this installation method instead',
    wechatTitle: 'Open this page in your phone browser first',
    wechatDescription: 'In WeChat, tap ··· at the top right and choose “Open in Browser”. If that option is unavailable, copy this page link and paste it into your phone browser. Your progress will stay with the link.',
    copyLink: 'Copy this page link',
    copied: 'Link copied. Paste it into your phone browser to continue.',
    copyFailed: 'Long-press the address bar to copy this page link, then open it in your phone browser.',
    harmonyTitle: 'HarmonyOS NEXT support is being verified',
    harmonyDescription: 'We will not direct you to an unverified Android package. Choose an available notification or web option below.',
    apkVerificationTitle: 'Check the package before downloading',
    apkVersion: 'Version',
    apkSize: 'File size',
    apkSha256: 'SHA-256',
    apkStep1: 'Confirm the version, size, and SHA-256 shown here.',
    apkStep2: 'Tap Continue to download from the controlled official handoff.',
    apkStep3: 'After installation, return here and tap “Open the App” to continue with the same link.',
    apkMissing: 'Package verification information is incomplete, so downloading is paused. Please choose another method or try again later.',
    recoveryToggle: 'Did the last step not open? View recovery options',
    recoveryTitle: 'You can continue from here',
    recoveryDescription: 'Return to this page whenever a store or download does not open. Choose another method instead of repeating the same failed step.',
    chooseAgain: 'Choose a different region',
    reloadOptions: 'Refresh available methods',
    officialWebsite: 'Go to the LUTA website',
    waitlist: 'Notify me when available',
    stateMissingTitle: 'This installation link needs to be refreshed',
    stateMissingDescription: 'The secure installation information is missing or expired. Please scan the original QR code again. You can also visit the official website without seeing a system error.',
    loadFailedTitle: 'Installation options are temporarily unavailable',
    loadFailedDescription: 'No destination has been opened. Refresh the options or visit the official website and try again later.',
    noOptionsTitle: 'No verified installation method is available right now',
    noOptionsDescription: 'We will not send you to an unverified store or package. Use the notification or official website options below.',
    privacy: 'Privacy',
    backHome: 'Official website',
    languageLabel: 'Language',
}

const zh = {
    metaTitle: '安全安装汝塔',
    brand: '汝塔',
    pageTitle: '安装汝塔',
    pageDescription: '选择最适合你的安装方式',
    openInstalledApp: '已经安装汝塔？打开 App',
    loadingTitle: '正在准备安装方式',
    loadingDescription: '我们正在核对当前可用的官方渠道。',
    retry: '重新获取',
    choiceLegend: '请选择适合你的地区',
    choiceHint: '这个选择只会调整推荐顺序。下方仍会保留所有当前可用的安装方式。',
    choiceHelpTitle: '不确定怎么选？',
    choiceHelpDescription: '在 App Store 搜索“汝塔”。能找到时选择“中国大陆”；找不到时选择“其他国家或地区”。',
    regionCnTitle: '中国大陆',
    regionCnDescription: '前往 App Store 安装',
    regionGlobalTitle: '其他国家或地区',
    regionGlobalDescription: '查看你所在地区当前可用的安装方式',
    recommended: '建议先试',
    otherOptions: '可选安装方式',
    androidOptionsTitle: '选择你平时下载手机应用的方式',
    allOptionsHint: '投放来源只影响排序，不会隐藏其他可用渠道。',
    noCompatibleChoiceTitle: '你选择的方式当前还未开放',
    noCompatibleChoiceDescription: '我们不会把你带到其他设备的商店或不可用地区。请在下方换一种方式，或先返回汝塔官网。',
    channelAppleCn: 'App Store · 中国大陆',
    channelAppleGlobal: 'App Store · 其他地区',
    channelGooglePlay: 'Google Play',
    channelApk: '官方 Android 安装包',
    channelOtherStore: '其他已核验应用商店',
    channelTestFlight: 'iPhone 内测版',
    channelWaitlist: '开放后通知我',
    channelWeb: '先在汝塔官网了解',
    channelUnknown: '其他官方方式',
    regionCnBadge: '中国大陆',
    regionGlobalBadge: '其他地区',
    regionUnknownBadge: '不限地区',
    statusAvailable: '当前可用',
    statusUnavailable: '暂未开放',
    statusUnverified: '信息待核验',
    continueAction: '继续',
    unavailableAction: '请选择其他方式',
    optionDefaultDescription: '继续前会再次核对可用性，再打开对应的官方页面。',
    mismatchHint: '这项与你刚才的偏好不同；如果你能正常使用，仍然可以选择。',
    mismatchAction: '我可以使用中国大陆安装方式',
    wechatTitle: '请先用手机浏览器打开本页',
    wechatDescription: '在微信右上角点击「···」，选择「在浏览器中打开」。如果没有这个选项，可以复制本页链接后粘贴到手机浏览器；安全安装状态会保留在链接中。',
    copyLink: '复制本页链接',
    copied: '链接已复制，请粘贴到手机浏览器继续。',
    copyFailed: '请长按地址栏复制本页链接，再粘贴到手机浏览器打开。',
    harmonyTitle: 'HarmonyOS NEXT 的安装支持仍在核验',
    harmonyDescription: '我们不会把你导向未经验证的 Android 安装包。请使用下方已开放的通知或网页方式。',
    apkVerificationTitle: '下载前先核对安装包',
    apkVersion: '版本',
    apkSize: '文件大小',
    apkSha256: 'SHA-256',
    apkStep1: '核对这里显示的版本、大小和 SHA-256。',
    apkStep2: '点击「继续」，通过受控的官方出口下载。',
    apkStep3: '安装完成后返回本页，点击“打开 App”恢复本次链接。',
    apkMissing: '安装包校验信息不完整，下载已暂停。请选择其他方式，或稍后重新获取。',
    recoveryToggle: '刚才没有打开？查看可恢复方式',
    recoveryTitle: '你可以从这里继续',
    recoveryDescription: '商店或下载没有打开时，随时返回本页换一种方式，不需要反复尝试同一个失败步骤。',
    chooseAgain: '重新选择常用地区',
    reloadOptions: '刷新可用方式',
    officialWebsite: '前往汝塔官网',
    waitlist: '开放后通知我',
    stateMissingTitle: '这个安装链接需要重新获取',
    stateMissingDescription: '安全安装信息缺失或已经失效，请重新扫描原二维码。你也可以先进入汝塔官网，不会看到系统报错。',
    loadFailedTitle: '暂时没有获取到安装方式',
    loadFailedDescription: '我们没有打开任何不确定的页面。你可以重新获取，或先进入官网稍后再试。',
    noOptionsTitle: '当前没有已核验的安装方式',
    noOptionsDescription: '我们不会把你导向未经验证的商店或安装包。请使用下方通知或官网入口。',
    privacy: '隐私政策',
    backHome: '汝塔官网',
    languageLabel: '语言',
}

const zhTW = {
    ...zh,
    metaTitle: '安全安裝汝塔',
    pageTitle: '安裝汝塔',
    pageDescription: '選擇最適合你的安裝方式',
    openInstalledApp: '已經安裝汝塔？開啟 App',
    apkStep3: '安裝完成後返回本頁，點擊「開啟 App」恢復本次連結。',
    loadingTitle: '正在準備安裝方式',
    loadingDescription: '我們正在核對目前可用的官方管道。',
    retry: '重新取得',
    choiceLegend: '請選擇適合你的地區',
    choiceHint: '這個選擇只會調整建議順序。下方仍會保留所有目前可用的安裝方式。',
    choiceHelpTitle: '不確定怎麼選？',
    choiceHelpDescription: '在 App Store 搜尋「汝塔」。找得到時選擇「中國大陸」；找不到時選擇「其他國家或地區」。',
    regionCnTitle: '中國大陸',
    regionCnDescription: '前往 App Store 安裝',
    regionGlobalTitle: '其他國家或地區',
    regionGlobalDescription: '查看你所在地區目前可用的安裝方式',
    otherOptions: '可選安裝方式',
    androidOptionsTitle: '選擇你平時下載手機 App 的方式',
    allOptionsHint: '投放來源只影響排序，不會隱藏其他可用管道。',
    noCompatibleChoiceTitle: '你選擇的方式目前尚未開放',
    noCompatibleChoiceDescription: '我們不會把你帶到其他裝置的商店或不可用地區。請在下方換一種方式，或先返回汝塔官網。',
    channelAppleCn: 'App Store · 中國大陸',
    channelAppleGlobal: 'App Store · 其他地區',
    channelApk: '官方 Android 安裝包',
    channelOtherStore: '其他已核驗應用程式商店',
    channelWaitlist: '開放後通知我',
    statusAvailable: '目前可用',
    statusUnavailable: '暫未開放',
    statusUnverified: '資訊待核驗',
    continueAction: '繼續',
    mismatchAction: '我可以使用中國大陸安裝方式',
    wechatTitle: '請先用手機瀏覽器開啟本頁',
    wechatDescription: '在微信右上角點擊「···」，選擇「在瀏覽器中開啟」。如果沒有這個選項，可以複製本頁連結後貼到手機瀏覽器；安全安裝狀態會保留在連結中。',
    copied: '連結已複製，請貼到手機瀏覽器繼續。',
    apkMissing: '安裝包驗證資訊不完整，下載已暫停。請選擇其他方式，或稍後重新取得。',
    recoveryToggle: '剛才沒有開啟？查看可恢復方式',
    recoveryTitle: '你可以從這裡繼續',
    reloadOptions: '重新整理可用方式',
    officialWebsite: '前往汝塔官網',
    stateMissingTitle: '這個安裝連結需要重新取得',
    loadFailedTitle: '暫時沒有取得安裝方式',
    noOptionsTitle: '目前沒有已核驗的安裝方式',
    privacy: '隱私政策',
    backHome: '汝塔官網',
    languageLabel: '語言',
}

const ja = {
    ...en,
    metaTitle: 'LUTAを安全にインストール',
    pageTitle: 'LUTAをインストール',
    pageDescription: '最適なインストール方法を選んでください。',
    openInstalledApp: 'LUTAをインストール済みですか？アプリを開く',
    apkStep3: 'インストール後にこのページへ戻り、「アプリを開く」を押して同じリンクから続けます。',
    choiceLegend: 'どちらの方法が使いやすいですか？',
    choiceHint: 'この選択は表示順だけを変えます。利用可能な方法はすべて下に残ります。',
    choiceHelpTitle: 'どちらを選ぶか分からない場合',
    choiceHelpDescription: 'App Store で「LUTA」を検索してください。見つかる場合は「中国本土」、見つからない場合は「その他の地域」を選びます。',
    regionCnTitle: '中国本土向けの方法',
    regionCnDescription: '中国本土で一般的に使える公式経路を優先',
    regionGlobalTitle: 'その他の地域向けの方法',
    regionGlobalDescription: 'その他の地域で一般的に使える公式経路を優先',
    otherOptions: '利用可能なインストール方法',
    androidOptionsTitle: '普段アプリをダウンロードする方法を選んでください',
    noCompatibleChoiceTitle: 'この方法は現在この端末では利用できません',
    noCompatibleChoiceDescription: '別の端末向けストアや利用できない地域には移動しません。下から別の方法を選ぶか、LUTA公式サイトに戻ってください。',
    channelAppleCn: 'App Store・中国本土',
    channelAppleGlobal: 'App Store・その他の地域',
    channelApk: '公式Androidパッケージ',
    channelOtherStore: '確認済みのその他のアプリストア',
    channelWaitlist: '利用可能になったら通知',
    continueAction: '続ける',
    mismatchAction: '代わりにこの方法を使う',
    wechatTitle: '先にスマートフォンのブラウザで開いてください',
    wechatDescription: 'WeChat右上の「···」から「ブラウザで開く」を選びます。見つからない場合は、このページのリンクをコピーしてブラウザに貼り付けてください。選択内容はリンクに保持されます。',
    recoveryToggle: '開きませんでしたか？復旧方法を見る',
    recoveryTitle: 'ここから続けられます',
    officialWebsite: 'LUTA公式サイトへ',
    privacy: 'プライバシー',
    backHome: '公式サイト',
    languageLabel: '言語',
}

const ko = {
    ...en,
    metaTitle: 'LUTA 안전하게 설치하기',
    pageTitle: 'LUTA 설치',
    pageDescription: '가장 적합한 설치 방법을 선택하세요.',
    openInstalledApp: 'LUTA가 이미 설치되어 있나요? 앱 열기',
    apkStep3: '설치 후 이 페이지로 돌아와 “앱 열기”를 눌러 같은 링크에서 계속하세요.',
    choiceLegend: '어디에서 설치하는 것이 더 편한가요?',
    choiceHint: '이 선택은 순서만 바꿉니다. 사용 가능한 모든 방법은 아래에 계속 표시됩니다.',
    choiceHelpTitle: '어떤 항목을 선택할지 모르겠나요?',
    choiceHelpDescription: 'App Store에서 “LUTA”를 검색하세요. 찾을 수 있으면 “중국 본토”, 찾을 수 없으면 “기타 국가 또는 지역”을 선택하세요.',
    regionCnTitle: '중국 본토에서 자주 쓰는 방법',
    regionCnDescription: '중국 본토에서 일반적으로 사용 가능한 공식 경로 우선',
    regionGlobalTitle: '기타 지역에서 자주 쓰는 방법',
    regionGlobalDescription: '기타 지역에서 일반적으로 사용 가능한 공식 경로 우선',
    otherOptions: '사용 가능한 설치 방법',
    androidOptionsTitle: '평소 휴대폰 앱을 다운로드하는 방법을 선택하세요',
    noCompatibleChoiceTitle: '선택한 방법은 현재 이 기기에서 사용할 수 없습니다',
    noCompatibleChoiceDescription: '다른 기기의 스토어나 사용할 수 없는 지역으로 보내지 않습니다. 아래에서 다른 방법을 선택하거나 LUTA 공식 웹사이트로 돌아가세요.',
    channelAppleCn: 'App Store · 중국 본토',
    channelAppleGlobal: 'App Store · 기타 지역',
    channelApk: '공식 Android 설치 파일',
    channelOtherStore: '검증된 기타 앱 스토어',
    channelWaitlist: '사용 가능할 때 알림 받기',
    continueAction: '계속',
    mismatchAction: '대신 이 설치 방법 사용',
    wechatTitle: '먼저 휴대폰 브라우저에서 이 페이지를 여세요',
    wechatDescription: 'WeChat 오른쪽 위의 「···」에서 「브라우저에서 열기」를 선택하세요. 보이지 않으면 이 페이지 링크를 복사해 휴대폰 브라우저에 붙여 넣으세요. 선택한 내용은 링크에 유지됩니다.',
    recoveryToggle: '열리지 않았나요? 복구 방법 보기',
    recoveryTitle: '여기에서 계속할 수 있습니다',
    officialWebsite: 'LUTA 공식 웹사이트',
    privacy: '개인정보처리방침',
    backHome: '공식 웹사이트',
    languageLabel: '언어',
}

const COPY_BY_LANGUAGE = { zh, zhTW, en, ja, ko }

export function getInstallCopy(language) {
    return COPY_BY_LANGUAGE[language] || zh
}

export const INSTALL_LANGUAGE_OPTIONS = [
    { code: 'zh', label: '简体中文' },
    { code: 'zhTW', label: '繁體中文' },
    { code: 'en', label: 'English' },
    { code: 'ja', label: '日本語' },
    { code: 'ko', label: '한국어' },
]
