const en = {
    metaTitle: 'Install LUTA',
    brand: 'LUTA',
    pageTitle: 'Install LUTA',
    pageDescription: 'Choose the official version for your device and region',
    iphone: 'iPhone',
    android: 'Android',
    recommended: 'Recommended',
    cnEdition: 'Mainland China edition',
    cnStore: 'Go to the App Store',
    globalEdition: 'International edition',
    globalStore: 'Go to the App Store',
    globalWaitlist: 'Not available in your region yet · Notify me when it becomes available',
    officialApk: 'Download from LUTA',
    officialApkFallback: 'Official Android package',
    googlePlay: 'Google Play',
    googlePlayDescription: 'Download from Google Play',
    channelTemporarilyUnavailable: 'Temporarily unavailable · View other options',
    otherChannel: 'Other official option',
    openInstalledApp: 'Already installed? Open LUTA',
    loading: 'Preparing your options…',
    opening: 'Opening…',
    wechatTitle: 'Continue in your phone browser',
    wechatDescription: 'Open this page in your browser to continue the download.',
    copyLink: 'Copy link',
    copied: 'Link copied. Paste it into your phone browser.',
    copyFailed: 'Copy the address from the address bar, then open it in your phone browser.',
    recoveryTitle: 'Did not open?',
    recoveryChoose: 'Choose another version',
    recoveryWebsite: 'Return to the LUTA website',
    terminalTitle: 'Choose another way to continue',
    terminalDescription: 'This option is not available right now. Choose another official way to continue.',
    noOptionsTitle: 'Downloads are being prepared',
    noOptionsDescription: 'We will only show a download when it is ready.',
    retry: 'Try again',
    apkDetails: 'View verification details',
    apkVersion: 'Version',
    apkSize: 'Size',
    apkSha256: 'SHA-256',
    officialWebsite: 'LUTA website',
    privacy: 'Privacy',
    languageLabel: 'Language',
}

const zh = {
    metaTitle: '安装汝塔',
    brand: '汝塔',
    pageTitle: '安装汝塔',
    pageDescription: '选择适合此设备和地区的官方版本',
    iphone: 'iPhone',
    android: '安卓',
    recommended: '推荐',
    cnEdition: '中国大陆版',
    cnStore: '前往 App Store',
    globalEdition: '国际版',
    globalStore: '前往 App Store',
    globalWaitlist: '所在地区暂未开放 · 开放后通知我',
    officialApk: '官网下载',
    officialApkFallback: '官方安卓安装包',
    googlePlay: 'Google Play',
    googlePlayDescription: '前往 Google Play 下载',
    channelTemporarilyUnavailable: '当前暂不可直接打开 · 查看其他方式',
    otherChannel: '其他官方方式',
    openInstalledApp: '已安装？打开汝塔',
    loading: '正在准备安装方式…',
    opening: '正在打开…',
    wechatTitle: '请在手机浏览器中继续',
    wechatDescription: '用浏览器打开本页，即可继续下载。',
    copyLink: '复制链接',
    copied: '链接已复制，请粘贴到手机浏览器打开。',
    copyFailed: '请复制地址栏中的链接，再用手机浏览器打开。',
    recoveryTitle: '没有打开？',
    recoveryChoose: '换一个版本',
    recoveryWebsite: '返回汝塔官网',
    terminalTitle: '换一种方式继续',
    terminalDescription: '此方式当前不可用，请选择其他官方方式继续。',
    noOptionsTitle: '下载方式正在准备中',
    noOptionsDescription: '准备完成后，我们会在这里提供可用入口。',
    retry: '重新获取',
    apkDetails: '查看校验信息',
    apkVersion: '版本',
    apkSize: '大小',
    apkSha256: 'SHA-256',
    officialWebsite: '汝塔官网',
    privacy: '隐私政策',
    languageLabel: '语言',
}

const zhTW = {
    metaTitle: '安裝汝塔',
    brand: '汝塔',
    pageTitle: '安裝汝塔',
    pageDescription: '選擇適合此裝置和地區的官方版本',
    iphone: 'iPhone',
    android: 'Android',
    recommended: '推薦',
    cnEdition: '中國大陸版',
    cnStore: '前往 App Store',
    globalEdition: '國際版',
    globalStore: '前往 App Store',
    globalWaitlist: '所在地區尚未開放 · 開放後通知我',
    officialApk: '官網下載',
    officialApkFallback: '官方 Android 安裝包',
    googlePlay: 'Google Play',
    googlePlayDescription: '前往 Google Play 下載',
    channelTemporarilyUnavailable: '目前暫時無法直接開啟 · 查看其他方式',
    otherChannel: '其他官方方式',
    openInstalledApp: '已安裝？開啟汝塔',
    loading: '正在準備安裝方式…',
    opening: '正在開啟…',
    wechatTitle: '請在手機瀏覽器中繼續',
    wechatDescription: '用瀏覽器開啟本頁，即可繼續下載。',
    copyLink: '複製連結',
    copied: '連結已複製，請貼到手機瀏覽器開啟。',
    copyFailed: '請複製網址列中的連結，再用手機瀏覽器開啟。',
    recoveryTitle: '沒有開啟？',
    recoveryChoose: '換一個版本',
    recoveryWebsite: '返回汝塔官網',
    terminalTitle: '換一種方式繼續',
    terminalDescription: '此方式目前無法使用，請選擇其他官方方式繼續。',
    noOptionsTitle: '下載方式正在準備中',
    noOptionsDescription: '準備完成後，我們會在這裡提供可用入口。',
    retry: '重新取得',
    apkDetails: '查看驗證資訊',
    apkVersion: '版本',
    apkSize: '大小',
    apkSha256: 'SHA-256',
    officialWebsite: '汝塔官網',
    privacy: '隱私權政策',
    languageLabel: '語言',
}

const ja = {
    metaTitle: 'LUTAをインストール',
    brand: 'LUTA',
    pageTitle: 'LUTAをインストール',
    pageDescription: '端末と地域に適した公式版を選択してください',
    iphone: 'iPhone',
    android: 'Android',
    recommended: 'おすすめ',
    cnEdition: '中国本土版',
    cnStore: 'App Storeへ',
    globalEdition: '国際版',
    globalStore: 'App Storeへ',
    globalWaitlist: 'お住まいの地域では現在利用できません · 利用可能になったら通知',
    officialApk: '公式サイトからダウンロード',
    officialApkFallback: '公式Androidパッケージ',
    googlePlay: 'Google Play',
    googlePlayDescription: 'Google Playからダウンロード',
    channelTemporarilyUnavailable: '現在は直接開けません · 別の方法を見る',
    otherChannel: 'その他の公式方法',
    openInstalledApp: 'インストール済みですか？LUTAを開く',
    loading: 'インストール方法を準備しています…',
    opening: '開いています…',
    wechatTitle: 'スマートフォンのブラウザで続けてください',
    wechatDescription: 'このページをブラウザで開くと、ダウンロードを続けられます。',
    copyLink: 'リンクをコピー',
    copied: 'リンクをコピーしました。スマートフォンのブラウザに貼り付けてください。',
    copyFailed: 'アドレスバーのリンクをコピーし、スマートフォンのブラウザで開いてください。',
    recoveryTitle: '開きませんでしたか？',
    recoveryChoose: '別のバージョンを選ぶ',
    recoveryWebsite: 'LUTA公式サイトへ戻る',
    terminalTitle: '別の方法で続ける',
    terminalDescription: 'この方法は現在利用できません。別の公式方法を選択してください。',
    noOptionsTitle: 'ダウンロードを準備しています',
    noOptionsDescription: '準備ができ次第、利用可能な方法を表示します。',
    retry: '再試行',
    apkDetails: '検証情報を見る',
    apkVersion: 'バージョン',
    apkSize: 'サイズ',
    apkSha256: 'SHA-256',
    officialWebsite: 'LUTA公式サイト',
    privacy: 'プライバシー',
    languageLabel: '言語',
}

const ko = {
    metaTitle: 'LUTA 설치',
    brand: 'LUTA',
    pageTitle: 'LUTA 설치',
    pageDescription: '기기와 지역에 맞는 공식 버전을 선택하세요',
    iphone: 'iPhone',
    android: 'Android',
    recommended: '추천',
    cnEdition: '중국 본토 버전',
    cnStore: 'App Store로 이동',
    globalEdition: '국제 버전',
    globalStore: 'App Store로 이동',
    globalWaitlist: '거주 지역에서는 아직 이용할 수 없습니다 · 이용 가능 알림 받기',
    officialApk: '공식 웹사이트에서 다운로드',
    officialApkFallback: '공식 Android 설치 파일',
    googlePlay: 'Google Play',
    googlePlayDescription: 'Google Play에서 다운로드',
    channelTemporarilyUnavailable: '현재 바로 열 수 없습니다 · 다른 방법 보기',
    otherChannel: '기타 공식 방법',
    openInstalledApp: '이미 설치했나요? LUTA 열기',
    loading: '설치 방법을 준비하고 있습니다…',
    opening: '열고 있습니다…',
    wechatTitle: '휴대폰 브라우저에서 계속하세요',
    wechatDescription: '이 페이지를 브라우저에서 열면 다운로드를 계속할 수 있습니다.',
    copyLink: '링크 복사',
    copied: '링크를 복사했습니다. 휴대폰 브라우저에 붙여 넣으세요.',
    copyFailed: '주소 표시줄의 링크를 복사한 후 휴대폰 브라우저에서 여세요.',
    recoveryTitle: '열리지 않았나요?',
    recoveryChoose: '다른 버전 선택',
    recoveryWebsite: 'LUTA 웹사이트로 돌아가기',
    terminalTitle: '다른 방법으로 계속하기',
    terminalDescription: '이 방법은 현재 사용할 수 없습니다. 다른 공식 방법을 선택해 계속하세요.',
    noOptionsTitle: '다운로드를 준비하고 있습니다',
    noOptionsDescription: '준비가 완료되면 사용 가능한 방법을 표시합니다.',
    retry: '다시 시도',
    apkDetails: '검증 정보 보기',
    apkVersion: '버전',
    apkSize: '크기',
    apkSha256: 'SHA-256',
    officialWebsite: 'LUTA 웹사이트',
    privacy: '개인정보처리방침',
    languageLabel: '언어',
}

const COPY_BY_LANGUAGE = { zh, zhTW, en, ja, ko }

export function getInstallCopy(language) {
    return COPY_BY_LANGUAGE[language] || zh
}

export const INSTALL_LANGUAGE_OPTIONS = [
    { code: 'zh', label: '简体中文' },
    { code: 'zhTW', label: '繁體中文' },
    { code: 'en', label: 'English' },
    { code: 'ja', label: '日本語' },
    { code: 'ko', label: '한국어' },
]
