const englishContent = {
    locale: 'en',
    localeKey: 'en',
    languageKey: 'en',
    path: '/global/en',
    metadata: {
        title: 'LUTA | Read Buddhist Classics. Build a Practice That Lasts.',
        description: 'Begin with the original text of Buddhist classics, use AI only to support understanding, and build a personal path of study and practice over time.',
        keywords: 'LUTA,Buddhist classics,scripture reading,AI-assisted understanding,practice planning,personal Buddhist practice',
    },
    brand: { name: '汝塔', latin: 'LUTA' },
    navigation: {
        label: 'Page navigation',
        skipToMain: 'Skip to main content',
        why: 'Why LUTA',
        capabilities: 'Product',
        principles: 'Our principles',
        getApp: 'Get the App',
    },
    localeSwitcher: {
        label: 'Switch page language',
        text: 'English',
        menuLabel: 'Choose page language',
    },
    hero: {
        eyebrow: 'Buddhist classics and lasting personal practice',
        desktopTitle: ['Read Buddhist classics.', 'Build a practice', 'that can last.'],
        mobileTitle: ['Read the classics.', 'Keep practice going.'],
        accessibleTitle: 'Read Buddhist classics and build a practice that can last.',
        lead: 'Begin with the original text, with AI supporting understanding. Let each reading, reflection, and act of practice become part of a personal path you can continue over time.',
        mobileLead: 'Original text first. AI supports understanding. Keep each step.',
        caption: 'Classic reading · Daily reflection · Tabao support',
        carouselLabel: 'LUTA product screens',
        carouselInstructions: 'Swipe or drag left and right, or use the arrow keys, to change the screen in the center.',
        carouselRoleDescription: 'carousel',
        slideRoleDescription: 'slide',
        visuals: [
            {
                image: 'wisdom',
                slot: 'start',
                label: 'Daily reflection',
                alt: 'LUTA daily reflection screen showing today’s contemplation and practice history',
                priority: false,
            },
            {
                image: 'reading',
                slot: 'center',
                label: 'Classic reading',
                alt: 'LUTA classic reading screen showing the original text, understanding tools, and audio controls',
                priority: true,
            },
            {
                image: 'tabao',
                slot: 'end',
                label: 'Tabao support',
                alt: 'LUTA Tabao screen supporting questions and understanding around a Buddhist classic',
                priority: false,
            },
        ],
    },
    why: {
        title: ['Classics are easy to find.', 'Understanding and continuing', 'take time.'],
        description: 'Finding a classic is only the beginning. The deeper work is understanding the original text, establishing a steady rhythm, and allowing every reading to become part of a longer journey of study and practice.',
        mobileDescription: 'From finding a classic, to understanding it, to building a path you can continue—LUTA helps each step stay connected.',
        journeyLabel: 'The LUTA product journey',
        journey: ['Understand the text', 'Build your path', 'Record the journey'],
    },
    stories: [
        {
            id: 'reading',
            chapter: 'Read the classics',
            title: ['Understand the classics,', 'beginning with the text.'],
            description: 'Read the original text and, when needed, explore its background, key ideas, and terminology—while keeping understanding grounded in the text itself.',
            mobileDescription: 'Read the original text and explore background, key ideas, and terminology when needed, while keeping understanding grounded in the text.',
            tone: 'paper',
            visualFirst: true,
            image: 'reading',
            imageAlt: 'LUTA classic reading screen showing the original text, understanding tools, and audio controls',
            caption: 'Reading · Original text and understanding tools',
            features: [
                ['The original text comes first', 'Read first, then explore further, without separating a passage from its full context.'],
                ['AI supports understanding', 'Use it to clarify background and concepts—not to replace the text, personal judgment, or living traditions.'],
                ['An unhurried reading experience', 'Tools appear only when needed, leaving your attention with the reading.'],
            ],
        },
        {
            id: 'practice',
            chapter: 'Personal practice',
            title: ['Build a steady rhythm,', 'so practice can continue.'],
            description: 'Turn what you hope to sustain into a clear plan, using goals, progress, and daily actions to shape a path of your own.',
            mobileDescription: 'Use plans, progress, and goals to turn a long-term intention into something you can do today.',
            tone: 'mist',
            visualFirst: false,
            image: 'practice',
            imageAlt: 'LUTA practice plan screen showing today’s reflection and ongoing progress',
            caption: 'Practice plan · Today’s reflection',
            features: [
                ['A clear plan for today', 'Arrange reading and practice as actions that can be completed today.'],
                ['Progress you can return to', 'See how far you have come and where the next step begins.'],
                ['Your path remains yours', 'The tool helps you establish a rhythm; it does not choose your practice for you.'],
            ],
        },
        {
            id: 'history',
            chapter: 'Your journey',
            title: ['Keep each reading,', 'reflection, and practice.'],
            description: 'Preserve what you have read, understood, and practiced, connecting separate moments into a personal journey you can revisit and continue.',
            mobileDescription: 'Connect separate moments into a personal journey you can revisit and continue.',
            tone: 'pine',
            visualFirst: true,
            image: 'history',
            imageAlt: 'LUTA home screen showing today’s reflection, reading activity, and personal practice history',
            caption: 'Your journey · Reading and practice history',
            features: [
                ['Every reading leaves a record', 'Each return to a classic becomes part of a longer journey.'],
                ['Reflections gather over time', 'Preserve what you understand now and later see how it has changed.'],
                ['Practice continues beyond reading', 'Connect plans and records to support long-term exploration.'],
            ],
        },
    ],
    principles: {
        title: ['Let technology step back,', 'so the classics and the person', 'remain at the center.'],
        items: [
            ['Respect tradition', 'Begin with the original text and respect traditional texts, interpretations, and transmission.'],
            ['AI only supports', 'AI can help clarify content and context, but it does not replace learning, judgment, or practice.'],
            ['Support long-term exploration', 'Bring reading, planning, and reflection together to support a steady personal journey.'],
        ],
    },
    finalCta: {
        title: 'Begin your journey with the classics.',
        mobileTitle: ['Begin your journey', 'with the classics.'],
        description: 'Let understanding and reflection become part of a personal path you can continue over time.',
    },
    store: {
        sectionLabel: 'Choose an installation method for this device',
        iosTab: 'iPhone',
        androidTab: 'Android / HarmonyOS',
        actions: {
            open_apple_store: { label: 'Download from the App Store', description: 'View and install the version currently available' },
            open_waitlist: { label: 'Notify me about iOS', description: 'Email me when it opens here' },
            open_google_play: { label: 'Download from Google Play', description: 'Install the official version through Google Play' },
            open_verified_apk: { label: 'View and download the official package', description: 'Review the version and file information before downloading' },
            expand_testflight: { label: 'Join the iOS beta', description: 'Open the two-step TestFlight installation guide' },
            open_testflight_app: { label: 'Step 1 · Download TestFlight', description: 'Return to this page after downloading; you do not need to open it first' },
            open_testflight_beta: { label: 'Step 2 · Install the LUTA beta', description: 'Follow Apple’s instructions to complete installation' },
            show_wechat_guide: { label: 'Open in your browser', description: 'Installation cannot start inside WeChat; first open this page in your system browser' },
            open_install_documentation: { label: 'View safe installation options', description: 'See the official installation guidance for this device' },
        },
        loading: 'Checking available installation options…',
        disabled: 'This installation option is temporarily unavailable. Please try again later or ask for help.',
        waitlistNote: 'Email is used only for this iOS notice. Complete the form to register.',
        testflightNote: 'Complete Step 1 first, then return to this page for Step 2.',
        testflightConfirm: {
            title: 'You’re about to open the App Store',
            description: 'After downloading TestFlight, return directly to this page and select Step 2. You do not need to open TestFlight first.',
            cancel: 'Not now',
            confirm: 'Continue to download',
        },
        wechatGuide: {
            title: 'Open this page in your system browser',
            description: 'Use the menu in the upper-right corner of WeChat and choose “Open in Browser.” When you return, we’ll show the safe installation options available for this device.',
            close: 'Got it',
        },
        help: 'Need installation help',
    },
    recovery: {
        preparingTitle: 'This link is still being prepared',
        pausedTitle: 'This link is currently paused',
        unavailableTitle: 'This link cannot continue right now',
        description: 'You did nothing wrong. We will not send you to an unavailable store; you can still view the installation options currently available on the official website.',
        primaryAction: 'View available installation options',
        dismiss: 'Close this message and continue browsing',
    },
    footer: {
        privacy: 'Privacy Policy',
        terms: 'Terms of Service',
        contact: 'Contact Us',
        help: 'Help Center',
        copyrightOwner: '深圳市师利千秋文化科技有限公司',
        copyrightRights: 'All rights reserved.',
        icp: '粤ICP备2025461997号-1',
    },
}

export default englishContent
