const englishContent = {
    locale: 'en',
    localeKey: 'en',
    languageKey: 'en',
    path: '/global/en',
    metadata: {
        title: 'LUTA | Read and Understand Chinese Buddhist Scriptures',
        description: 'Read original Chinese Buddhist scriptures with plain-language translations, use AI-assisted explanations when needed, and keep a record of your reading and reflection.',
        keywords: 'LUTA,Chinese Buddhist scriptures,plain-language translation,Buddhist reading app,AI-assisted scripture reading,reading reflection',
    },
    brand: { name: '汝塔', latin: 'LUTA' },
    navigation: {
        label: 'Page navigation',
        skipToMain: 'Skip to main content',
        why: 'Why LUTA',
        capabilities: 'What LUTA does',
        principles: 'Our principles',
        getApp: 'Start reading for free',
    },
    localeSwitcher: {
        label: 'Switch page language',
        text: 'English',
        menuLabel: 'Choose page language',
    },
    hero: {
        eyebrow: 'Chinese Buddhist scripture reading worldwide',
        desktopTitle: ['Read the scriptures.', 'Understand their wisdom.', 'Practice, every day.'],
        mobileTitle: ['Read the sutras', 'Find their wisdom', 'Practice every day'],
        accessibleTitle: 'Read the scriptures, understand their wisdom, and bring practice into daily life.',
        lead: 'Not sure where to begin—or how to understand a difficult passage? Read original Chinese scriptures with plain-language translations, use AI-assisted explanations when needed, and keep a record of your reading and reflection.',
        mobileLead: 'Read Chinese scriptures and translations, use AI when needed, and record insights.',
        primaryCta: {
            label: 'Start reading for free',
            description: 'Core reading stays free · Official install',
        },
        caption: 'Scripture reading · TaBao support · Plans and records',
        carouselLabel: 'LUTA product screens',
        carouselInstructions: 'Swipe or drag left and right, or use the arrow keys, to change the screen in the center.',
        carouselRoleDescription: 'carousel',
        slideRoleDescription: 'slide',
        visuals: [
            {
                image: 'wisdom',
                slot: 'start',
                label: 'Daily reflection',
                alt: 'LUTA daily reflection screen showing today’s reflection and study history',
                priority: false,
            },
            {
                image: 'reading',
                slot: 'center',
                label: 'Scripture reading',
                alt: 'LUTA scripture reading screen showing the canonical text, explanation tools, and audio controls',
                priority: true,
            },
            {
                image: 'tabao',
                slot: 'end',
                label: 'TaBao support',
                alt: 'LUTA TaBao screen supporting questions and understanding around a Buddhist scripture',
                priority: false,
            },
        ],
    },
    why: {
        title: ['The scriptures are easy to find.', 'Understanding them—and returning to them—', 'is harder.'],
        description: 'Finding a scripture is only the beginning. The real challenge is to understand the text, find a steady reading pace, and carry each reading forward as part of a longer journey.',
        mobileDescription: 'From reading and understanding to finding your pace and keeping a record, LUTA helps each step stay connected.',
        journeyLabel: 'The LUTA product journey',
        journey: ['Read the scripture', 'Find your reading pace', 'Keep a record'],
    },
    stories: [
        {
            id: 'reading',
            chapter: 'Scripture reading',
            title: ['Understanding begins', 'with the text.'],
            description: 'Read the scripture itself, then turn to background, key ideas, and terminology when needed—without losing sight of the passage and its wider context.',
            mobileDescription: 'Read the scripture itself, then explore background, key ideas, and terminology when needed—without losing sight of the passage.',
            tone: 'paper',
            visualFirst: true,
            image: 'reading',
            imageAlt: 'LUTA scripture reading screen showing the canonical text, explanation tools, and audio controls',
            caption: 'Scripture reading · Text and explanation tools',
            features: [
                ['The text comes first', 'Read the passage before exploring further, and keep it within its full context.'],
                ['AI remains an aid', 'Use it to clarify language, context, and key ideas—not to replace scripture, traditional commentaries, personal judgment, or guidance from teachers.'],
                ['A focused reading experience', 'Tools appear only when needed, leaving your attention with the text.'],
            ],
        },
        {
            id: 'practice',
            chapter: 'Reading and study plan',
            title: ['Find a reading pace', 'you can sustain.'],
            description: 'Turn long-term reading and study intentions into a clear plan with defined goals, visible progress, and manageable actions for today.',
            mobileDescription: 'Turn long-term intentions into clear actions you can complete today.',
            tone: 'mist',
            visualFirst: false,
            image: 'practice',
            imageAlt: 'LUTA reading and study plan screen showing today’s reflection and ongoing progress',
            caption: 'Reading and study plan · Daily reflection',
            features: [
                ['A clear plan for today', 'Break reading and reflection into manageable actions for the day.'],
                ['Progress you can return to', 'See what you have completed and where the next step begins.'],
                ['Your path remains yours', 'LUTA helps you plan and keep track; it does not choose your path for you.'],
            ],
        },
        {
            id: 'history',
            chapter: 'Your journey',
            title: ['Keep a record of what you read,', 'reflect on, and practice.'],
            description: 'Preserve what you have read, reflected on, and practiced, and connect separate moments into a personal journey you can revisit and continue.',
            mobileDescription: 'Connect separate moments into a personal journey you can revisit and continue.',
            tone: 'pine',
            visualFirst: true,
            image: 'history',
            imageAlt: 'LUTA home screen showing today’s reflection, reading activity, and personal study history',
            caption: 'Your journey · Reading and study history',
            features: [
                ['Every reading leaves a record', 'Each return to a scripture becomes part of a longer journey.'],
                ['Reflections gather over time', 'Preserve what you understand now and later see how it has changed.'],
                ['Plans connect with progress', 'Bring daily actions and long-term records together.'],
            ],
        },
    ],
    principles: {
        title: ['Let technology step back,', 'so the scriptures and the reader', 'remain at the center.'],
        items: [
            ['Rooted in tradition', 'Ground the experience in scripture and respect established texts, commentaries, and living traditions.'],
            ['AI is an aid, not an authority', 'It can clarify language and context, but it does not replace scripture, traditional commentaries, personal judgment, or teachers.'],
            ['Made for long-term study', 'Bring reading, planning, and reflection together in a journey you can sustain.'],
        ],
    },
    finalCta: {
        title: 'Begin with one passage.',
        mobileTitle: ['Begin with', 'one passage.'],
        description: 'Read, understand, plan, and keep a record—at a reading pace you can sustain.',
    },
    store: {
        sectionLabel: 'Choose the official download option for this device',
        appLanguageNotice: 'LUTA is currently a Chinese-language app.',
        iosTab: 'iPhone',
        androidTab: 'Android / HarmonyOS',
        actions: {
            open_apple_store: { label: 'Download from the App Store', description: 'View LUTA on the App Store and install the current release' },
            open_waitlist: { label: 'Notify me when LUTA is available in my region', description: 'Get an email when LUTA becomes available in your region' },
            open_google_play: { label: 'Download from Google Play', description: 'Install the official version through Google Play' },
            open_verified_apk: { label: 'Download the verified Android package', description: 'Review the version and file information before downloading' },
            expand_testflight: { label: 'Try the newest LUTA', description: 'Beta access in 2 simple steps' },
            open_testflight_app: { label: 'Step 1 · Install Apple’s official tool', description: 'Requires iOS 16 or later. When it finishes, do not tap Open—return to this page' },
            open_testflight_beta: { label: 'Step 2 · Install the newest LUTA', description: 'Select this after returning, then follow the installation prompts' },
            show_wechat_guide: { label: 'Open in your browser', description: 'Installation cannot start inside WeChat; first open this page in your system browser' },
            open_install_documentation: { label: 'View safe installation options', description: 'See the official installation guidance for this device' },
        },
        loading: 'Checking available installation options…',
        disabled: 'This installation option is temporarily unavailable. Please try again later or ask for help.',
        waitlistNote: 'Your email will be used only to notify you when iOS access opens in your region. Complete the form to register.',
        testflightNote: 'Seeing “Enter Redeem Code”? You do not need a code. Return to your browser and select “Step 2 · Install the newest LUTA.”',
        testflightConfirm: {
            title: 'Return to this page after installation',
            description: 'This is Apple’s tool for beta installation. Do not tap Open after installing it. If you see “Enter Redeem Code,” leave it blank, close the tool, and return here.',
            cancel: 'Not now',
            confirm: 'Got it, install the tool',
        },
        wechatGuide: {
            title: 'Open this page in your system browser',
            description: 'Use the menu in the upper-right corner of WeChat and choose “Open in Browser.” When you return, we’ll show the safe installation options available for this device.',
            close: 'Got it',
        },
        help: 'Need installation help',
    },
    recovery: {
        preparingTitle: 'This link is still being prepared',
        pausedTitle: 'This link is currently paused',
        unavailableTitle: 'This link is temporarily unavailable',
        description: 'Your action was valid. We will not send you to an unavailable store; you can still view the official download options currently available on the LUTA website.',
        primaryAction: 'View available installation options',
        dismiss: 'Close this message and continue browsing',
    },
    footer: {
        privacy: 'Privacy Policy',
        terms: 'Terms of Service',
        contact: 'Contact Us',
        help: 'Help Center',
        copyrightOwner: '深圳市师利千秋文化科技有限公司',
        copyrightRights: 'All rights reserved.',
        icp: '粤ICP备2025461997号-1',
    },
}

export default englishContent
