const japaneseContent = {
    locale: 'ja',
    localeKey: 'ja',
    languageKey: 'ja',
    path: '/global/ja',
    metadata: {
        title: 'LUTA｜仏教経典を読み、学びと実践を続けるためのツール',
        description: '仏教経典の原文から始め、AIは理解を支えるためにだけ使い、自分自身の学びと実践の歩みを長く続けます。',
        keywords: 'LUTA,仏教経典,経典を読む,AI理解支援,実践計画,仏教の学び',
    },
    brand: { name: '汝塔', latin: 'LUTA' },
    navigation: {
        label: 'ページナビゲーション',
        skipToMain: 'メインコンテンツへ移動',
        why: 'LUTAを選ぶ理由',
        capabilities: '製品の特長',
        principles: '私たちの原則',
        getApp: 'アプリを入手',
    },
    localeSwitcher: {
        label: 'ページの言語を切り替える',
        text: '日本語',
        menuLabel: 'ページの言語を選択',
    },
    hero: {
        eyebrow: '仏教経典を読み、学びと実践を続けるために',
        desktopTitle: ['仏教経典を読み解き、', '自分の学びと実践を', '長く続ける。'],
        mobileTitle: ['経典を読み解き、', '学びを続ける。'],
        accessibleTitle: '仏教経典を読み解き、自分の学びと実践を長く続ける。',
        lead: '経典の原文から始め、AIは理解を助けるためにだけ使います。一回ごとの読書、考察、実践を、長く続けられる自分自身の歩みとして積み重ねます。',
        mobileLead: '原文を中心に、AIは理解を補助。一歩ずつ記録します。',
        caption: '経典を読む · 今日の気づき · TaBaoのサポート',
        carouselLabel: 'LUTAの製品画面',
        carouselInstructions: '左右にスワイプまたはドラッグするか、左右の矢印キーで中央の画面を切り替えます。',
        carouselRoleDescription: 'カルーセル',
        slideRoleDescription: 'スライド',
        visuals: [
            {
                image: 'wisdom',
                slot: 'start',
                label: '今日の気づき',
                alt: 'LUTAの今日の気づき画面。今日の観照と学び・実践の記録を表示',
                priority: false,
            },
            {
                image: 'reading',
                slot: 'center',
                label: '経典を読む',
                alt: 'LUTAの経典閲覧画面。原文、理解を助けるツール、音声機能を表示',
                priority: true,
            },
            {
                image: 'tabao',
                slot: 'end',
                label: 'TaBaoのサポート',
                alt: 'LUTAのTaBao画面。経典の内容に沿った理解支援と質問機能を表示',
                priority: false,
            },
        ],
    },
    why: {
        title: ['経典を見つけることは、', '難しくありません。', '理解し、続けることが大切です。'],
        description: '一冊の経典を見つけることは始まりにすぎません。原文を理解し、安定したリズムをつくり、一回ごとの読書を長い学びと実践の歩みにつなげることが大切です。',
        mobileDescription: '経典を見つけ、理解し、自分の歩みをつくるまで。LUTAは一つひとつの段階をつなぎます。',
        journeyLabel: 'LUTAで続ける学びと実践',
        journey: ['経典を理解する', '自分の歩みを整える', '積み重ねを残す'],
    },
    stories: [
        {
            id: 'reading',
            chapter: '経典を読む',
            title: ['理解は、', '原文を読むことから。'],
            description: '経典の原文を読み、必要なときだけ背景、教えの流れ、用語の意味を確かめます。理解の中心は、いつも原文に置きます。',
            mobileDescription: '原文を読み、必要なときだけ背景や用語を確認し、理解の中心を経典そのものに置きます。',
            tone: 'paper',
            visualFirst: true,
            image: 'reading',
            imageAlt: 'LUTAの経典閲覧画面。原文、理解を助けるツール、音声機能を表示',
            caption: '経典閲覧 · 原文と理解を助けるツール',
            features: [
                ['原文を中心に', 'まず読み、その後に理解を広げます。経文を文脈から切り離しません。'],
                ['AIは理解を補助', '背景や概念の整理を助けますが、原文、個人の判断、伝統的な継承に代わるものではありません。'],
                ['静かに読める体験', 'ツールは必要なときだけ現れ、注意を経典に戻します。'],
            ],
        },
        {
            id: 'practice',
            chapter: '学びと実践の計画',
            title: ['自分のリズムを整え、', '無理なく続ける。'],
            description: '長く続けたいことを明確な計画にし、目標、進み具合、毎日の行動から、自分自身の歩みを整えます。',
            mobileDescription: '計画、進み具合、目標を通して、長く続けたいことを今日できる行動にします。',
            tone: 'mist',
            visualFirst: false,
            image: 'practice',
            imageAlt: 'LUTAの実践計画画面。今日の観照と継続状況を表示',
            caption: '学びと実践の計画 · 今日の観照',
            features: [
                ['今日やることが見える', '経典を読むことと実践することを、今日できる行動として整えます。'],
                ['歩みを振り返れる', 'どこまで進んだか、次の一歩をどこから始めるかが分かります。'],
                ['進み方は自分で決める', 'ツールはリズムづくりを助けますが、歩む道を代わりに決めません。'],
            ],
        },
        {
            id: 'history',
            chapter: '自分の歩み',
            title: ['読むこと、考えること、', '実践することを積み重ねる。'],
            description: '読んだ内容、そのときの理解、続けてきた実践を残し、別々の瞬間を振り返り、続けられる自分自身の歩みにつなげます。',
            mobileDescription: '別々の瞬間を、振り返りながら続けられる自分自身の歩みにつなげます。',
            tone: 'pine',
            visualFirst: true,
            image: 'history',
            imageAlt: 'LUTAのホーム画面。今日の観照、読書内容、学びと実践の記録を表示',
            caption: '自分の歩み · 読書と実践の記録',
            features: [
                ['読むたびに記録が残る', '経典を開く一回一回が、長い歩みの一部になります。'],
                ['考えが少しずつ積み重なる', '今の理解を残し、後から自分の変化を振り返れます。'],
                ['実践が続いていく', '計画と記録をつなぎ、長い探究を支えます。'],
            ],
        },
    ],
    principles: {
        title: ['技術は一歩後ろに。', '経典と読む人を、', '中心に。'],
        items: [
            ['伝統を尊重する', '経典の原文を基礎とし、伝統的なテキスト、解釈、継承を尊重します。'],
            ['AIはあくまで補助', '内容と文脈の理解を助けますが、個人の学び、判断、実践に代わるものではありません。'],
            ['長く続く学びを支える', '読むこと、計画すること、記録することをつなぎ、安定して続く個人の歩みを支えます。'],
        ],
    },
    finalCta: {
        title: '経典との歩みを、ここから。',
        mobileTitle: ['経典との歩みを、', 'ここから。'],
        description: '理解と記録を、長く続けられる自分自身の歩みにつなげます。',
    },
    store: {
        sectionLabel: 'この端末に適した公式ダウンロード方法を選択',
        appLanguageNotice: '現在、LUTAのアプリ内容は中国語で提供されています。',
        iosTab: 'iPhone',
        androidTab: 'Android / HarmonyOS',
        actions: {
            open_apple_store: { label: 'App Storeからダウンロード', description: 'App StoreでLUTAの正式版を確認してインストール' },
            open_waitlist: { label: 'お住まいの地域で利用可能になったら通知', description: '利用可能になり次第、メールでお知らせします' },
            open_google_play: { label: 'Google Playからダウンロード', description: 'Google Playから公式版をインストール' },
            open_verified_apk: { label: '検証済みの公式Androidファイルをダウンロード', description: 'バージョンとファイル情報を確認してからダウンロード' },
            expand_testflight: { label: '最新のLUTAを試す', description: 'ベータ版は2ステップで利用できます' },
            open_testflight_app: { label: 'ステップ1 · Apple公式ツールをインストール', description: 'iOS 16以降が必要です。完了後は「開く」を押さず、このページに戻ってください' },
            open_testflight_beta: { label: 'ステップ2 · 最新のLUTAをインストール', description: 'このページに戻ってここを選び、案内に従ってインストールしてください' },
            show_wechat_guide: { label: 'ブラウザで開く', description: 'WeChat内ではインストールできないため、システムブラウザでこのページを開いてください' },
            open_install_documentation: { label: '安全なインストール方法を見る', description: 'この端末に適した公式インストール案内を確認' },
        },
        loading: '利用できるインストール方法を確認しています…',
        disabled: 'このインストール方法は現在利用できません。後でもう一度お試しいただくか、ヘルプをご利用ください。',
        waitlistNote: 'メールは、お住まいの地域でiOS版が利用可能になった際の通知にのみ使用します。登録にはフォームの送信完了が必要です。',
        testflightNote: '「コードを入力」が表示されても、入力は不要です。ブラウザに戻り「ステップ2 · 最新のLUTAをインストール」を選んでください。',
        testflightConfirm: {
            title: 'インストール後、このページに戻ってください',
            description: 'これはApple公式のベータ版インストール用ツールです。インストール後は「開く」を押さないでください。「コードを入力」が表示された場合は何も入力せず、ツールを閉じてこのページに戻ってください。',
            cancel: '今はインストールしない',
            confirm: '確認してインストールへ',
        },
        wechatGuide: {
            title: 'システムブラウザで開いてください',
            description: 'WeChat右上のメニューから「ブラウザで開く」を選択してください。戻ってきた後、この端末で利用できる安全なインストール方法をご案内します。',
            close: '分かりました',
        },
        help: 'インストールのヘルプ',
    },
    recovery: {
        preparingTitle: 'このリンクは現在準備中です',
        pausedTitle: 'このリンクは現在一時停止中です',
        unavailableTitle: 'このリンクは現在ご利用いただけません',
        description: 'お客様の操作に問題はありません。利用できないストアには移動せず、公式サイトで現在利用できるインストール方法をご確認いただけます。',
        primaryAction: '利用できるインストール方法を見る',
        dismiss: '案内を閉じてサイトを見る',
    },
    footer: {
        privacy: 'プライバシーポリシー',
        terms: '利用規約',
        contact: 'お問い合わせ',
        help: 'ヘルプセンター',
        copyrightOwner: '深圳市师利千秋文化科技有限公司',
        copyrightRights: 'All rights reserved.',
        icp: '粤ICP备2025461997号-1',
    },
}

export default japaneseContent
