const koreanContent = {
    locale: 'ko',
    localeKey: 'ko',
    languageKey: 'ko',
    path: '/global/ko',
    metadata: {
        title: 'LUTA | 중국어 불교 경전을 읽고 이해하는 도구',
        description: '중국어 불교 경전 원문과 쉬운 번역을 읽고, 필요할 때 AI의 이해 지원을 받으며, 읽기와 사유의 여정을 기록합니다.',
        keywords: 'LUTA,중국어 불교 경전,경전 읽기,쉬운 번역,AI 이해 지원,읽기 기록',
    },
    brand: { name: '汝塔', latin: 'LUTA' },
    navigation: {
        label: '페이지 탐색',
        skipToMain: '주요 콘텐츠로 이동',
        why: 'LUTA를 선택하는 이유',
        capabilities: '제품 기능',
        principles: '우리가 지키는 원칙',
        getApp: '무료로 읽기 시작',
    },
    localeSwitcher: {
        label: '페이지 언어 전환',
        text: '한국어',
        menuLabel: '페이지 언어 선택',
    },
    hero: {
        eyebrow: '전 세계 중국어 독자를 위한 불교 경전 읽기와 이해 도구',
        desktopTitle: ['경전 읽기부터 시작해', '경문 속 지혜를 이해하고', '수행을 일상으로 이어 갑니다'],
        mobileTitle: ['경전을 읽고', '지혜를 이해해', '수행을 일상으로'],
        accessibleTitle: '경전 읽기부터 시작해 경문 속 지혜를 이해하고 수행을 일상으로 이어 갑니다.',
        lead: '경전은 방대해 어디서부터 시작할지 막막하고, 그 뜻을 이해하기도 쉽지 않습니다. LUTA는 중국어 경전 원문과 쉬운 번역을 읽고, 필요할 때 AI의 이해 지원을 받으며, 읽기와 사유의 여정을 기록하도록 돕습니다.',
        mobileLead: '중국어 경전 원문과 쉬운 번역을 읽고, 필요할 때 AI의 이해 지원을 받으며, 매번의 읽기와 사유를 기록합니다.',
        primaryCta: {
            label: '무료로 읽기 시작',
            description: '기본 읽기는 계속 무료 · 이 기기에 맞는 공식 설치 방법을 엽니다',
        },
        caption: '경전 읽기 · 오늘의 지혜 · TaBao의 도움',
        carouselLabel: 'LUTA 제품 화면',
        carouselInstructions: '좌우로 스와이프하거나 드래그하거나, 좌우 화살표 키로 가운데 화면을 바꿀 수 있습니다.',
        carouselRoleDescription: '캐러셀',
        slideRoleDescription: '슬라이드',
        visuals: [
            {
                image: 'wisdom',
                slot: 'start',
                label: '오늘의 지혜',
                alt: 'LUTA 오늘의 지혜 화면. 오늘의 관조와 수행 기록을 표시',
                priority: false,
            },
            {
                image: 'reading',
                slot: 'center',
                label: '경전 읽기',
                alt: 'LUTA 경전 읽기 화면. 경전 원문, 이해 도구, 듣기 기능을 표시',
                priority: true,
            },
            {
                image: 'tabao',
                slot: 'end',
                label: 'TaBao의 도움',
                alt: 'LUTA TaBao 화면. 경전 내용을 바탕으로 이해와 질문을 돕는 기능을 표시',
                priority: false,
            },
        ],
    },
    why: {
        title: ['경전은 쉽게 찾을 수 있습니다.', '이해하고 꾸준히 이어 가는 일은', '시간이 필요합니다.'],
        description: '한 권의 경전을 찾는 것은 시작일 뿐입니다. 원문을 이해하고, 안정적인 리듬을 만들고, 매번의 읽기를 긴 수행 여정 속에 남기는 일이 더 중요합니다.',
        mobileDescription: '경전을 찾고, 이해하고, 나만의 수행 길을 세우는 과정까지 LUTA가 모든 단계를 이어 줍니다.',
        journeyLabel: 'LUTA 수행 여정',
        journey: ['경전 이해하기', '수행의 길 세우기', '여정 기록하기'],
    },
    stories: [
        {
            id: 'reading',
            chapter: '경전 읽기',
            title: ['경전을 이해하는 일은,', '원문에서 시작합니다.'],
            description: '경전 원문을 읽고 필요한 순간에만 배경, 가르침의 맥락, 용어의 뜻을 확인하여 이해가 언제나 경전 자체로 돌아오게 합니다.',
            mobileDescription: '경전 원문을 읽고 필요할 때 배경과 용어를 확인하며, 이해의 중심을 경전 자체에 둡니다.',
            tone: 'paper',
            visualFirst: true,
            image: 'reading',
            imageAlt: 'LUTA 경전 읽기 화면. 경전 원문, 이해 도구, 듣기 기능을 표시',
            caption: '경전 읽기 · 원문과 이해 도구',
            features: [
                ['경전 원문을 중심에', '먼저 읽고 그다음 이해를 넓히며, 구절을 전체 맥락에서 떼어 놓지 않습니다.'],
                ['AI는 이해를 돕는 역할만', '배경과 개념을 정리하도록 돕지만 원문, 개인의 판단, 전통의 전승을 대신하지 않습니다.'],
                ['차분한 읽기 경험', '도구는 필요할 때만 나타나며, 주의가 경전에 머물도록 돕습니다.'],
            ],
        },
        {
            id: 'practice',
            chapter: '수행 계획',
            title: ['리듬을 만들고,', '수행을 꾸준히 이어 갑니다.'],
            description: '오래 이어 가고 싶은 일을 분명한 계획으로 만들고, 목표와 진도, 매일의 행동을 통해 나만의 수행 길을 세웁니다.',
            mobileDescription: '계획, 진도, 목표를 통해 오래 이어 가고 싶은 일을 오늘 실천할 수 있는 행동으로 만듭니다.',
            tone: 'mist',
            visualFirst: false,
            image: 'practice',
            imageAlt: 'LUTA 수행 계획 화면. 오늘의 관조와 수행 진도를 표시',
            caption: '수행 계획 · 오늘의 관조',
            features: [
                ['오늘의 계획이 분명하게', '경전 읽기와 실천을 오늘 완료할 수 있는 행동으로 정리합니다.'],
                ['진도를 계속 확인', '얼마나 걸어왔는지, 다음 걸음은 어디에서 시작할지 알 수 있습니다.'],
                ['수행의 길은 스스로 결정', '도구는 리듬을 만드는 일을 돕지만 개인의 수행 선택을 대신하지 않습니다.'],
            ],
        },
        {
            id: 'history',
            chapter: '나의 수행 여정',
            title: ['읽고 생각하고 실천한', '모든 순간을 쌓습니다.'],
            description: '읽은 내용, 그때의 이해, 이어 온 실천을 기록하여 흩어진 순간들을 다시 돌아보고 계속 이어 갈 수 있는 나만의 수행 여정으로 연결합니다.',
            mobileDescription: '흩어진 순간들을 다시 돌아보고 계속 이어 갈 수 있는 나만의 수행 여정으로 연결합니다.',
            tone: 'pine',
            visualFirst: true,
            image: 'history',
            imageAlt: 'LUTA 홈 화면. 오늘의 관조, 읽은 경전, 개인 수행 기록을 표시',
            caption: '나의 수행 여정 · 읽기와 실천 기록',
            features: [
                ['읽을 때마다 기록이 남습니다', '경전을 펼치는 모든 순간이 긴 여정의 일부가 됩니다.'],
                ['생각이 차곡차곡 쌓입니다', '지금의 이해를 남기고 나중에 자신의 변화를 돌아볼 수 있습니다.'],
                ['실천이 계속 이어집니다', '계획과 기록을 연결하여 오랜 탐구를 돕습니다.'],
            ],
        },
    ],
    principles: {
        title: ['기술은 한 걸음 물러나고,', '경전과 사람이', '중심에 남습니다.'],
        items: [
            ['전통을 존중합니다', '경전 원문을 바탕으로 전통 문헌, 해석 체계, 전승을 존중합니다.'],
            ['AI는 보조 역할만 합니다', '내용과 맥락의 이해를 돕지만 개인의 배움, 판단, 수행을 대신하지 않습니다.'],
            ['오래 이어지는 여정을 돕습니다', '읽기, 계획, 기록을 연결하여 안정적이고 지속적인 개인 수행을 돕습니다.'],
        ],
    },
    finalCta: {
        title: '경전과 함께하는 여정을 시작하세요.',
        mobileTitle: ['경전과 함께하는', '여정을 시작하세요.'],
        description: '이해하고 기록하는 시간을 오래 이어 갈 수 있는 나만의 여정으로 만드세요.',
    },
    store: {
        sectionLabel: '이 기기에 맞는 공식 다운로드 방법 선택',
        appLanguageNotice: '현재 LUTA 앱의 콘텐츠는 중국어로 제공됩니다.',
        iosTab: 'iPhone',
        androidTab: 'Android / HarmonyOS',
        actions: {
            open_apple_store: { label: 'App Store에서 다운로드', description: 'App Store에서 LUTA 정식 버전을 확인하고 설치' },
            open_waitlist: { label: '거주 지역에서 이용 가능해지면 알림 받기', description: '이용 가능해지면 이메일로 알려 드립니다' },
            open_google_play: { label: 'Google Play에서 다운로드', description: 'Google Play를 통해 공식 버전 설치' },
            open_verified_apk: { label: '검증된 공식 Android 파일 다운로드', description: '버전과 파일 정보를 확인한 후 다운로드' },
            expand_testflight: { label: '최신 LUTA 체험하기', description: '베타 버전은 2단계로 설치합니다' },
            open_testflight_app: { label: '1단계 · Apple 공식 도구 설치', description: 'iOS 16 이상이 필요합니다. 설치 후 “열기”를 누르지 말고 이 페이지로 돌아오세요' },
            open_testflight_beta: { label: '2단계 · 최신 LUTA 설치', description: '이 페이지로 돌아와 여기를 누른 뒤 안내에 따라 설치하세요' },
            show_wechat_guide: { label: '브라우저에서 열기', description: 'WeChat에서는 바로 설치할 수 없습니다. 시스템 브라우저에서 이 페이지를 열어 주세요' },
            open_install_documentation: { label: '안전한 설치 방법 보기', description: '이 기기에 맞는 공식 설치 안내 확인' },
        },
        loading: '사용 가능한 설치 방법을 확인하고 있습니다…',
        disabled: '이 설치 방법은 현재 사용할 수 없습니다. 잠시 후 다시 시도하거나 도움을 요청해 주세요.',
        waitlistNote: '이메일은 거주 지역에서 iOS 버전을 이용할 수 있게 되었을 때 알림을 보내는 용도로만 사용합니다. 등록하려면 양식 제출을 완료해 주세요.',
        testflightNote: '“교환 코드 입력” 화면이 보여도 입력할 필요가 없습니다. 브라우저로 돌아와 “2단계 · 최신 LUTA 설치”를 누르세요.',
        testflightConfirm: {
            title: '설치 후 이 페이지로 돌아오세요',
            description: 'Apple에서 제공하는 베타 설치용 공식 도구입니다. 설치 후 “열기”를 누르지 마세요. “교환 코드 입력” 화면이 보이면 아무것도 입력하지 말고 도구를 닫은 뒤 이 페이지로 돌아오세요.',
            cancel: '지금은 설치하지 않기',
            confirm: '확인하고 설치하기',
        },
        wechatGuide: {
            title: '시스템 브라우저에서 열어 주세요',
            description: 'WeChat 오른쪽 위 메뉴에서 “브라우저에서 열기”를 선택하세요. 돌아오면 이 기기에서 사용할 수 있는 안전한 설치 방법을 안내합니다.',
            close: '확인',
        },
        help: '설치 도움 받기',
    },
    recovery: {
        preparingTitle: '이 링크는 아직 준비 중입니다',
        pausedTitle: '이 링크는 현재 일시 중지되었습니다',
        unavailableTitle: '이 링크는 지금 계속할 수 없습니다',
        description: '사용자님의 잘못이 아닙니다. 이용할 수 없는 스토어로 보내지 않으며, 공식 웹사이트에서 현재 사용할 수 있는 설치 방법을 확인할 수 있습니다.',
        primaryAction: '사용 가능한 설치 방법 보기',
        dismiss: '안내를 닫고 계속 둘러보기',
    },
    footer: {
        privacy: '개인정보처리방침',
        terms: '이용약관',
        contact: '문의하기',
        help: '도움말 센터',
        copyrightOwner: '深圳市师利千秋文化科技有限公司',
        copyrightRights: 'All rights reserved.',
        icp: '粤ICP备2025461997号-1',
    },
}

export default koreanContent
