import englishContent from './marketing/en.js'
import japaneseContent from './marketing/ja.js'
import koreanContent from './marketing/ko.js'
import { MARKETING_LOCALE_KEYS } from '../lib/marketingLocales.js'

export const MARKETING_LOCALES = MARKETING_LOCALE_KEYS

const sharedPaths = Object.freeze({
    'zh-cn': '/global/zh-cn',
    'zh-tw': '/global/zh-tw',
})

const content = {
    'zh-cn': {
        locale: 'zh-CN',
        localeKey: 'zh-cn',
        languageKey: 'zh',
        path: sharedPaths['zh-cn'],
        metadata: {
            title: '汝塔 LUTA｜经典阅读与个人修学工具',
            description: '从佛教经典原文出发，借助 AI 辅助理解，建立并记录属于自己的长期修学路径。',
            keywords: '汝塔,LUTA,佛教经典,经典阅读,AI辅助理解,修学计划,个人修学',
        },
        brand: { name: '汝塔', latin: 'LUTA' },
        navigation: {
            label: '页面导航',
            skipToMain: '跳到主要内容',
            why: '为什么是汝塔',
            capabilities: '产品能力',
            principles: '我们的原则',
            getApp: '获取 App',
        },
        localeSwitcher: {
            label: '切换到繁体中文',
            text: '繁體中文',
            menuLabel: '选择页面语言',
        },
        hero: {
            eyebrow: '面向全球中文用户的数字修学工具',
            desktopTitle: ['读懂佛教经典，', '建立自己的', '长期修学路径。'],
            mobileTitle: ['读懂佛教经典，', '建立个人修学路径。'],
            accessibleTitle: '读懂佛教经典，建立自己的长期修学路径。',
            lead: '从经典原文出发，AI 辅助理解。把每一次阅读、思考与实践，沉淀为可以长期继续的个人修学历程。',
            mobileLead: '从经典原文出发，AI 辅助理解。记录每一次长期探索。',
            caption: '经典阅读 · 今日慧语 · 塔宝陪伴',
            carouselLabel: '汝塔产品界面',
            carouselInstructions: '左右滑动、拖动，或使用左右方向键切换中间展示的界面。',
            carouselRoleDescription: '轮播图',
            slideRoleDescription: '界面',
            visuals: [
                {
                    image: 'wisdom',
                    slot: 'start',
                    label: '今日慧语',
                    alt: '汝塔今日慧语界面，展示每日观照与修学记录',
                    priority: false,
                },
                {
                    image: 'reading',
                    slot: 'center',
                    label: '经典阅读',
                    alt: '汝塔经典阅读界面，展示经文原文、辅助理解工具和听读入口',
                    priority: true,
                },
                {
                    image: 'tabao',
                    slot: 'end',
                    label: '塔宝陪伴',
                    alt: '汝塔塔宝界面，展示围绕经典内容的辅助理解与问答',
                    priority: false,
                },
            ],
        },
        why: {
            title: ['经典容易获得。', '理解与坚持，', '才是长期的事。'],
            description: '找到一部经典只是开始。真正困难的是理解原文、形成稳定节奏，并让每一次阅读都能在长期修学中留下痕迹。',
            mobileDescription: '从找到经典，到理解经典，再到建立属于自己的长期修学路径，汝塔让每一步彼此连接。',
            journeyLabel: '汝塔产品路径',
            journey: ['读懂经典', '建立路径', '沉淀历程'],
        },
        stories: [
            {
                id: 'reading',
                chapter: '阅读经典',
                title: ['读懂经典，', '从原文开始。'],
                description: '阅读经典原文，并在需要时查看内容背景、义理脉络与术语解释，让理解始终回到文本本身。',
                mobileDescription: '阅读经典原文，并在需要时查看背景、义理与术语解释，让理解始终回到文本本身。',
                tone: 'paper',
                visualFirst: true,
                image: 'reading',
                imageAlt: '汝塔经典阅读界面，展示经文原文、辅助理解工具和听读入口',
                caption: '阅读界面 · 原文与理解工具',
                features: [
                    ['经典原文为本', '先阅读，再延伸；保留经文的完整语境。'],
                    ['AI 辅助理解', '帮助梳理背景与概念，不替代原文、个人判断与传统传承。'],
                    ['沉浸阅读体验', '工具只在需要时出现，让注意力留在阅读上。'],
                ],
            },
            {
                id: 'practice',
                chapter: '修学计划',
                title: ['建立节奏，', '让修学可以继续。'],
                description: '把想要长期坚持的内容变成清晰的计划，以目标、进度和每日行动建立属于自己的修学路径。',
                mobileDescription: '通过计划、进度与目标，把想要长期坚持的内容变成今天能够完成的行动。',
                tone: 'mist',
                visualFirst: false,
                image: 'practice',
                imageAlt: '汝塔修学计划界面，展示今日观照和修学进度',
                caption: '修学计划 · 今日观照',
                features: [
                    ['计划清晰可见', '把经典与实践安排为今天能够完成的行动。'],
                    ['进度持续反馈', '知道已经走了多远，也知道下一步从哪里开始。'],
                    ['路径由您决定', '工具帮助建立节奏，不替代个人的修学选择。'],
                ],
            },
            {
                id: 'history',
                chapter: '个人历程',
                title: ['沉淀每一次阅读、', '思考与实践。'],
                description: '记录读过的内容、当下的思考与持续实践，把零散片段连接成一段可回望、可继续的个人修学历程。',
                mobileDescription: '把零散片段连接成一段可回望、可继续的个人修学历程。',
                tone: 'pine',
                visualFirst: true,
                image: 'history',
                imageAlt: '汝塔首页界面，展示今日观照、阅读内容和个人修学记录',
                caption: '个人历程 · 阅读与实践记录',
                features: [
                    ['阅读留下记录', '每一次进入经典，都成为长期历程的一部分。'],
                    ['思考逐渐累积', '保存当下的理解，日后回看自己的变化。'],
                    ['实践持续发生', '让计划与记录连接，支持长期探索。'],
                ],
            },
        ],
        principles: {
            title: ['技术退后一步，', '让经典与人', '留在中心。'],
            items: [
                ['尊重传统', '以经典原文为基础，保持对传统文本与解释体系的尊重。'],
                ['AI 只作辅助', '帮助理解内容与语境，不代替个人学习、判断和修行实践。'],
                ['支持长期探索', '通过阅读、计划与记录，支持稳定而持续的个人修学历程。'],
            ],
        },
        finalCta: {
            title: '开始您的经典探索。',
            mobileTitle: ['开始您的', '经典探索。'],
            description: '让理解与记录，成为一段可以长期继续的个人旅程。',
        },
        store: {
            sectionLabel: '选择适用的安装方式',
            iosTab: 'iPhone',
            androidTab: 'Android / HarmonyOS',
            actions: {
                open_apple_store: { label: '前往 App Store 下载', description: '查看并安装当前可用版本' },
                open_waitlist: { label: 'iOS 开放时通知我', description: '留下邮箱，等你所在地区开放后通知你' },
                open_google_play: { label: '前往 Google Play 下载', description: '通过 Google Play 安装官方版本' },
                open_verified_apk: { label: '查看并下载官方安装包', description: '核对版本与文件信息后下载' },
                expand_testflight: { label: '参与 iOS 内测', description: '展开 TestFlight 两步安装指引' },
                open_testflight_app: { label: '第 1 步 · 下载 TestFlight', description: '下载后回到本页面，无需先打开' },
                open_testflight_beta: { label: '第 2 步 · 安装内测版汝塔', description: '按 Apple 指引完成内测版安装' },
                show_wechat_guide: { label: '在浏览器中打开', description: '微信中无法直接安装，请先用系统浏览器打开本页' },
                open_install_documentation: { label: '查看安全安装方式', description: '查看适合此设备的官方安装说明' },
            },
            loading: '正在确认可用的安装方式…',
            disabled: '当前安装方式暂不可用，请稍后重试或获取帮助',
            waitlistNote: '邮箱仅用于 iOS 开放通知。点击按钮后，请在表单中完成提交；未完成表单不会登记邮箱。',
            testflightNote: '请先完成第 1 步，再从本页面进入第 2 步。',
            testflightConfirm: {
                title: '即将前往 App Store',
                description: '下载 TestFlight 后请直接回到本页面，再点击第 2 步完成安装；无需先打开 TestFlight。',
                cancel: '暂不前往',
                confirm: '好的，前往下载',
            },
            wechatGuide: {
                title: '请在系统浏览器中打开',
                description: '点击微信右上角的菜单，再选择“在浏览器中打开”。返回本页后，我们会继续提供适用的安全安装方式。',
                close: '我知道了',
            },
            help: '需要安装帮助',
        },
        recovery: {
            preparingTitle: '这条链接还在准备中',
            pausedTitle: '这条链接已暂停使用',
            unavailableTitle: '这条链接暂时无法继续',
            description: '你没有做错任何事。我们不会把你带到不可用的商店；你仍可查看官网当前可用的安装方式。',
            primaryAction: '查看可用安装方式',
            dismiss: '关闭提示并继续浏览官网',
        },
        footer: {
            privacy: '隐私政策',
            terms: '使用协议',
            contact: '联系我们',
            help: '帮助中心',
            copyrightOwner: '深圳市师利千秋文化科技有限公司',
            copyrightRights: '保留所有权利.',
            icp: '粤ICP备2025461997号-1',
        },
    },
    'zh-tw': {
        locale: 'zh-TW',
        localeKey: 'zh-tw',
        languageKey: 'zhTW',
        path: sharedPaths['zh-tw'],
        metadata: {
            title: '汝塔 LUTA｜經典閱讀與個人修學工具',
            description: '從佛教經典原文出發，借助 AI 輔助理解，建立並記錄屬於自己的長期修學路徑。',
            keywords: '汝塔,LUTA,佛教經典,經典閱讀,AI輔助理解,修學計畫,個人修學',
        },
        brand: { name: '汝塔', latin: 'LUTA' },
        navigation: {
            label: '頁面導覽',
            skipToMain: '跳到主要內容',
            why: '為什麼是汝塔',
            capabilities: '產品能力',
            principles: '我們的原則',
            getApp: '取得 App',
        },
        localeSwitcher: {
            label: '切換到簡體中文',
            text: '简体中文',
            menuLabel: '選擇頁面語言',
        },
        hero: {
            eyebrow: '面向全球中文使用者的數位修學工具',
            desktopTitle: ['讀懂佛教經典，', '建立自己的', '長期修學路徑。'],
            mobileTitle: ['讀懂佛教經典，', '建立個人修學路徑。'],
            accessibleTitle: '讀懂佛教經典，建立自己的長期修學路徑。',
            lead: '從經典原文出發，AI 輔助理解。把每一次閱讀、思考與實踐，沉澱為可以長期繼續的個人修學歷程。',
            mobileLead: '從經典原文出發，AI 輔助理解。記錄每一次長期探索。',
            caption: '經典閱讀 · 今日慧語 · 塔寶陪伴',
            carouselLabel: '汝塔產品介面',
            carouselInstructions: '左右滑動、拖動，或使用左右方向鍵切換中央顯示的介面。',
            carouselRoleDescription: '輪播圖',
            slideRoleDescription: '介面',
            visuals: [
                {
                    image: 'wisdom',
                    slot: 'start',
                    label: '今日慧語',
                    alt: '汝塔今日慧語介面，展示每日觀照與修學記錄',
                    priority: false,
                },
                {
                    image: 'reading',
                    slot: 'center',
                    label: '經典閱讀',
                    alt: '汝塔經典閱讀介面，展示經文原文、輔助理解工具和聽讀入口',
                    priority: true,
                },
                {
                    image: 'tabao',
                    slot: 'end',
                    label: '塔寶陪伴',
                    alt: '汝塔塔寶介面，展示圍繞經典內容的輔助理解與問答',
                    priority: false,
                },
            ],
        },
        why: {
            title: ['經典容易獲得。', '理解與堅持，', '才是長期的事。'],
            description: '找到一部經典只是開始。真正困難的是理解原文、形成穩定節奏，並讓每一次閱讀都能在長期修學中留下痕跡。',
            mobileDescription: '從找到經典，到理解經典，再到建立屬於自己的長期修學路徑，汝塔讓每一步彼此連接。',
            journeyLabel: '汝塔產品路徑',
            journey: ['讀懂經典', '建立路徑', '沉澱歷程'],
        },
        stories: [
            {
                id: 'reading',
                chapter: '閱讀經典',
                title: ['讀懂經典，', '從原文開始。'],
                description: '閱讀經典原文，並在需要時查看內容背景、義理脈絡與術語解釋，讓理解始終回到文本本身。',
                mobileDescription: '閱讀經典原文，並在需要時查看背景、義理與術語解釋，讓理解始終回到文本本身。',
                tone: 'paper',
                visualFirst: true,
                image: 'reading',
                imageAlt: '汝塔經典閱讀介面，展示經文原文、輔助理解工具和聽讀入口',
                caption: '閱讀介面 · 原文與理解工具',
                features: [
                    ['經典原文為本', '先閱讀，再延伸；保留經文的完整語境。'],
                    ['AI 輔助理解', '協助梳理背景與概念，不取代原文、個人判斷與傳統傳承。'],
                    ['沉浸閱讀體驗', '工具只在需要時出現，讓注意力留在閱讀上。'],
                ],
            },
            {
                id: 'practice',
                chapter: '修學計畫',
                title: ['建立節奏，', '讓修學可以繼續。'],
                description: '把想要長期堅持的內容變成清晰的計畫，以目標、進度和每日行動建立屬於自己的修學路徑。',
                mobileDescription: '透過計畫、進度與目標，把想要長期堅持的內容變成今天能夠完成的行動。',
                tone: 'mist',
                visualFirst: false,
                image: 'practice',
                imageAlt: '汝塔修學計畫介面，展示今日觀照和修學進度',
                caption: '修學計畫 · 今日觀照',
                features: [
                    ['計畫清晰可見', '把經典與實踐安排為今天能夠完成的行動。'],
                    ['進度持續回饋', '知道已經走了多遠，也知道下一步從哪裡開始。'],
                    ['路徑由您決定', '工具協助建立節奏，不取代個人的修學選擇。'],
                ],
            },
            {
                id: 'history',
                chapter: '個人歷程',
                title: ['沉澱每一次閱讀、', '思考與實踐。'],
                description: '記錄讀過的內容、當下的思考與持續實踐，把零散片段連接成一段可回望、可繼續的個人修學歷程。',
                mobileDescription: '把零散片段連接成一段可回望、可繼續的個人修學歷程。',
                tone: 'pine',
                visualFirst: true,
                image: 'history',
                imageAlt: '汝塔首頁介面，展示今日觀照、閱讀內容和個人修學記錄',
                caption: '個人歷程 · 閱讀與實踐記錄',
                features: [
                    ['閱讀留下記錄', '每一次進入經典，都成為長期歷程的一部分。'],
                    ['思考逐漸累積', '保存當下的理解，日後回看自己的變化。'],
                    ['實踐持續發生', '讓計畫與記錄連接，支持長期探索。'],
                ],
            },
        ],
        principles: {
            title: ['技術退後一步，', '讓經典與人', '留在中心。'],
            items: [
                ['尊重傳統', '以經典原文為基礎，保持對傳統文本與解釋體系的尊重。'],
                ['AI 只作輔助', '協助理解內容與語境，不取代個人學習、判斷和修行實踐。'],
                ['支持長期探索', '透過閱讀、計畫與記錄，支持穩定而持續的個人修學歷程。'],
            ],
        },
        finalCta: {
            title: '開始您的經典探索。',
            mobileTitle: ['開始您的', '經典探索。'],
            description: '讓理解與記錄，成為一段可以長期繼續的個人旅程。',
        },
        store: {
            sectionLabel: '選擇適用的安裝方式',
            iosTab: 'iPhone',
            androidTab: 'Android / HarmonyOS',
            actions: {
                open_apple_store: { label: '前往 App Store 下載', description: '查看並安裝目前可用版本' },
                open_waitlist: { label: 'iOS 開放時通知我', description: '留下電子郵件，等所在地區開放後通知你' },
                open_google_play: { label: '前往 Google Play 下載', description: '透過 Google Play 安裝官方版本' },
                open_verified_apk: { label: '查看並下載官方安裝包', description: '核對版本與檔案資訊後下載' },
                expand_testflight: { label: '參與 iOS 內測', description: '展開 TestFlight 兩步安裝指引' },
                open_testflight_app: { label: '第 1 步 · 下載 TestFlight', description: '下載後回到本頁面，無需先開啟' },
                open_testflight_beta: { label: '第 2 步 · 安裝內測版汝塔', description: '依 Apple 指引完成內測版安裝' },
                show_wechat_guide: { label: '在瀏覽器中開啟', description: '微信中無法直接安裝，請先用系統瀏覽器開啟本頁' },
                open_install_documentation: { label: '查看安全安裝方式', description: '查看適合此裝置的官方安裝說明' },
            },
            loading: '正在確認可用的安裝方式…',
            disabled: '目前安裝方式暫不可用，請稍後重試或取得協助',
            waitlistNote: '電子郵件僅用於 iOS 開放通知。點擊按鈕後，請在表單中完成提交；未完成表單不會登記電子郵件。',
            testflightNote: '請先完成第 1 步，再從本頁面進入第 2 步。',
            testflightConfirm: {
                title: '即將前往 App Store',
                description: '下載 TestFlight 後請直接回到本頁面，再點擊第 2 步完成安裝；無需先開啟 TestFlight。',
                cancel: '暫不前往',
                confirm: '好的，前往下載',
            },
            wechatGuide: {
                title: '請在系統瀏覽器中開啟',
                description: '點擊微信右上角的選單，再選擇「在瀏覽器中開啟」。返回本頁後，我們會繼續提供適用的安全安裝方式。',
                close: '我知道了',
            },
            help: '需要安裝協助',
        },
        recovery: {
            preparingTitle: '這條連結仍在準備中',
            pausedTitle: '這條連結已暫停使用',
            unavailableTitle: '這條連結暫時無法繼續',
            description: '你沒有做錯任何事。我們不會把你帶到無法使用的商店；你仍可查看官網目前可用的安裝方式。',
            primaryAction: '查看可用安裝方式',
            dismiss: '關閉提示並繼續瀏覽官網',
        },
        footer: {
            privacy: '隱私政策',
            terms: '使用協議',
            contact: '聯絡我們',
            help: '幫助中心',
            copyrightOwner: '深圳市师利千秋文化科技有限公司',
            copyrightRights: '保留所有權利.',
            icp: '粤ICP备2025461997号-1',
        },
    },
    en: englishContent,
    ja: japaneseContent,
    ko: koreanContent,
}

export const MARKETING_CONTENT = Object.freeze(content)

export function formatMarketingCopyright(owner, rights, year = new Date().getFullYear()) {
    return `© ${year} ${owner}. ${rights}`
}

export function getMarketingContent(localeKey) {
    const value = MARKETING_CONTENT[localeKey]
    if (!value) throw new Error(`Unsupported marketing locale: ${localeKey}`)
    return value
}
