import englishContent from './marketing/en.js'
import japaneseContent from './marketing/ja.js'
import koreanContent from './marketing/ko.js'
import { MARKETING_LOCALE_KEYS } from '../lib/marketingLocales.js'

export const MARKETING_LOCALES = MARKETING_LOCALE_KEYS

const sharedPaths = Object.freeze({
    'zh-cn': '/global/zh-cn',
    'zh-tw': '/global/zh-tw',
})

const content = {
    'zh-cn': {
        locale: 'zh-CN',
        localeKey: 'zh-cn',
        languageKey: 'zh',
        path: sharedPaths['zh-cn'],
        metadata: {
            title: '汝塔 LUTA｜佛教经典阅读与修学辅助工具',
            description: '从佛教经典原文开始，在需要时获得 AI 辅助理解，并通过计划与记录建立可以持续的个人修学历程。',
            keywords: '汝塔,LUTA,佛教经典,经典阅读,AI辅助理解,修学计划,个人修学',
        },
        brand: { name: '汝塔', latin: 'LUTA' },
        navigation: {
            label: '页面导航',
            skipToMain: '跳到主要内容',
            why: '为什么选择汝塔',
            capabilities: '汝塔能做什么',
            principles: '我们的原则',
            getApp: '下载汝塔',
        },
        localeSwitcher: {
            label: '切换到繁体中文',
            text: '繁體中文',
            menuLabel: '选择页面语言',
        },
        hero: {
            eyebrow: '面向全球中文读者的佛教经典阅读与修学辅助工具',
            desktopTitle: ['从经典原文开始，', '建立自己的', '长期修学路径。'],
            mobileTitle: ['从经典原文开始，', '建立自己的修学路径。'],
            accessibleTitle: '从经典原文开始，建立自己的长期修学路径。',
            lead: '阅读佛教经典原文，在需要时获得 AI 辅助理解，并通过计划、进度与记录，让每一次阅读、思考与实践逐渐连接成可回望、可继续的个人历程。',
            mobileLead: '从经典原文开始，AI 辅助理解。记录每一次阅读、思考与实践。',
            caption: '经典阅读 · 塔宝辅助 · 计划与记录',
            carouselLabel: '汝塔产品界面',
            carouselInstructions: '左右滑动、拖动，或使用左右方向键切换中间展示的界面。',
            carouselRoleDescription: '轮播图',
            slideRoleDescription: '界面',
            visuals: [
                {
                    image: 'wisdom',
                    slot: 'start',
                    label: '今日慧语',
                    alt: '汝塔今日慧语界面，展示每日观照与修学记录',
                    priority: false,
                },
                {
                    image: 'reading',
                    slot: 'center',
                    label: '经典阅读',
                    alt: '汝塔经典阅读界面，展示经文原文、辅助理解工具和听读入口',
                    priority: true,
                },
                {
                    image: 'tabao',
                    slot: 'end',
                    label: '塔宝辅助',
                    alt: '汝塔塔宝界面，展示围绕经典内容的辅助理解与问答',
                    priority: false,
                },
            ],
        },
        why: {
            title: ['经典并不难找。', '难的是理解，', '并持续读下去。'],
            description: '找到一部经典只是开始。真正的挑战，是理解原文、建立稳定节奏，并把零散的阅读、思考与实践积累为一段可以继续的个人历程。',
            mobileDescription: '从阅读经典、辅助理解，到建立节奏并留下记录，汝塔让每一步彼此连接。',
            journeyLabel: '汝塔产品路径',
            journey: ['阅读经典', '建立节奏', '沉淀历程'],
        },
        stories: [
            {
                id: 'reading',
                chapter: '阅读经典',
                title: ['理解经典，', '从原文开始。'],
                description: '阅读经典原文；需要时，再查看背景、义理脉络与术语解释，让辅助理解始终回到经文本身。',
                mobileDescription: '阅读经典原文；需要时，再查看背景、义理与术语解释，让辅助理解始终回到经文本身。',
                tone: 'paper',
                visualFirst: true,
                image: 'reading',
                imageAlt: '汝塔经典阅读界面，展示经文原文、辅助理解工具和听读入口',
                caption: '阅读界面 · 原文与理解工具',
                features: [
                    ['经典原文为本', '先读原文，再作延伸，保留经文的完整语境。'],
                    ['AI 仅作辅助', '帮助梳理背景、概念与上下文，不替代经典原文、传统注疏或个人判断。'],
                    ['专注阅读体验', '工具只在需要时出现，让注意力留在经文上。'],
                ],
            },
            {
                id: 'practice',
                chapter: '修学计划',
                title: ['建立节奏，', '让长期修学落到每天。'],
                description: '将想长期坚持的阅读与实践拆解为清晰计划，通过目标、进度和每日任务，建立适合自己的修学节奏。',
                mobileDescription: '通过计划、目标与进度，把长期意愿变成今天可以完成的行动。',
                tone: 'mist',
                visualFirst: false,
                image: 'practice',
                imageAlt: '汝塔修学计划界面，展示今日观照和修学进度',
                caption: '修学计划 · 今日观照',
                features: [
                    ['今日任务清晰', '把阅读与实践拆解为今天可以完成的行动。'],
                    ['进度持续可见', '知道已经完成了什么，也知道下一步从哪里开始。'],
                    ['路径由您决定', '工具帮助规划与记录，不替代个人的修学选择。'],
                ],
            },
            {
                id: 'history',
                chapter: '个人历程',
                title: ['记录每一次阅读、', '思考与实践。'],
                description: '保存读过的内容、当下的思考与持续实践，把零散片段连接成一段可回望、可继续的个人修学历程。',
                mobileDescription: '把零散片段连接成一段可回望、可继续的个人修学历程。',
                tone: 'pine',
                visualFirst: true,
                image: 'history',
                imageAlt: '汝塔首页界面，展示今日观照、阅读内容和个人修学记录',
                caption: '个人历程 · 阅读与实践记录',
                features: [
                    ['阅读留下记录', '每一次进入经典，都成为个人历程的一部分。'],
                    ['思考逐渐累积', '保存当下的理解，日后回看自己的变化。'],
                    ['计划连接记录', '让今天的行动与长期历程彼此连接。'],
                ],
            },
        ],
        principles: {
            title: ['技术退后一步，', '让经典与人', '留在中心。'],
            items: [
                ['尊重传统', '以经典原文为基础，尊重传统文本、注疏与解释脉络。'],
                ['AI 仅作辅助', '帮助理解内容与语境，不替代经典原文、传统注疏、个人判断或老师指导。'],
                ['支持长期探索', '通过阅读、计划与记录，支持稳定而持续的个人修学历程。'],
            ],
        },
        finalCta: {
            title: '从一段经典开始。',
            mobileTitle: ['从一段经典', '开始。'],
            description: '让阅读、理解、计划与记录，逐渐连接成一段可以长期继续的个人历程。',
        },
        store: {
            sectionLabel: '选择适合此设备的下载方式',
            appLanguageNotice: '',
            iosTab: 'iPhone',
            androidTab: 'Android / HarmonyOS',
            actions: {
                open_apple_store: { label: '前往 App Store 下载', description: '前往 App Store 查看并安装正式版本' },
                open_waitlist: { label: '所在地区开放后通知我', description: '所在地区开放后，我们将通过邮件通知您' },
                open_google_play: { label: '前往 Google Play 下载', description: '通过 Google Play 安装官方版本' },
                open_verified_apk: { label: '下载经校验的官方 Android 安装包', description: '核对版本与文件信息后下载' },
                expand_testflight: { label: '体验新版汝塔', description: '内测版，需要完成 2 步' },
                open_testflight_app: { label: '第 1 步 · 安装苹果官方工具', description: '支持 iOS 16 及以上；安装完成不要点“打开”，请直接返回本页面' },
                open_testflight_beta: { label: '第 2 步 · 安装新版汝塔', description: '返回本页面点击这里，再按提示完成安装' },
                show_wechat_guide: { label: '在浏览器中打开', description: '微信中无法直接安装，请先用系统浏览器打开本页' },
                open_install_documentation: { label: '查看安全安装方式', description: '查看适合此设备的官方安装说明' },
            },
            loading: '正在确认可用的安装方式…',
            disabled: '当前安装方式暂不可用，请稍后重试或获取帮助',
            waitlistNote: '邮箱仅用于所在地区的 iOS 开放通知。点击按钮后，请完成表单提交；未提交的表单不会登记邮箱。',
            testflightNote: '看到“输入兑换码”？不用填写。返回浏览器，点击“第 2 步 · 安装新版汝塔”即可。',
            testflightConfirm: {
                title: '安装后，请直接返回本页面',
                description: '这是苹果提供的内测安装工具。安装完成后不要点“打开”；若直接打开后看到“输入兑换码”，无需填写，关闭后回到本页面即可。',
                cancel: '暂不安装',
                confirm: '记住了，去安装',
            },
            wechatGuide: {
                title: '请在系统浏览器中打开',
                description: '点击微信右上角的菜单，再选择“在浏览器中打开”。返回本页后，我们会继续提供适用的安全安装方式。',
                close: '我知道了',
            },
            help: '需要安装帮助',
        },
        recovery: {
            preparingTitle: '这条链接还在准备中',
            pausedTitle: '这条链接已暂停使用',
            unavailableTitle: '此链接暂时不可用',
            description: '无需担心，您的操作没有问题。我们不会将您带到不可用的商店；您仍可查看官网当前可用的下载方式。',
            primaryAction: '查看可用安装方式',
            dismiss: '关闭提示并继续浏览官网',
        },
        footer: {
            privacy: '隐私政策',
            terms: '使用协议',
            contact: '联系我们',
            help: '帮助中心',
            copyrightOwner: '深圳市师利千秋文化科技有限公司',
            copyrightRights: '保留所有权利。',
            icp: '粤ICP备2025461997号-1',
        },
    },
    'zh-tw': {
        locale: 'zh-TW',
        localeKey: 'zh-tw',
        languageKey: 'zhTW',
        path: sharedPaths['zh-tw'],
        metadata: {
            title: '汝塔 LUTA｜佛教經典閱讀與修學輔助工具',
            description: '從佛教經典原文開始，在需要時獲得 AI 輔助理解，並透過計畫與記錄建立可以持續的個人修學歷程。',
            keywords: '汝塔,LUTA,佛教經典,經典閱讀,AI輔助理解,修學計畫,個人修學',
        },
        brand: { name: '汝塔', latin: 'LUTA' },
        navigation: {
            label: '頁面導覽',
            skipToMain: '跳到主要內容',
            why: '為什麼選擇汝塔',
            capabilities: '汝塔能做什麼',
            principles: '我們的原則',
            getApp: '下載汝塔',
        },
        localeSwitcher: {
            label: '切換到簡體中文',
            text: '简体中文',
            menuLabel: '選擇頁面語言',
        },
        hero: {
            eyebrow: '面向全球中文讀者的佛教經典閱讀與修學輔助工具',
            desktopTitle: ['從經典原文開始，', '建立自己的', '長期修學路徑。'],
            mobileTitle: ['從經典原文開始，', '建立自己的修學路徑。'],
            accessibleTitle: '從經典原文開始，建立自己的長期修學路徑。',
            lead: '閱讀佛教經典原文，在需要時獲得 AI 輔助理解，並透過計畫、進度與記錄，讓每一次閱讀、思考與實踐逐漸連接成可回望、可繼續的個人歷程。',
            mobileLead: '從經典原文開始，AI 輔助理解。記錄每一次閱讀、思考與實踐。',
            caption: '經典閱讀 · 塔寶輔助 · 計畫與記錄',
            carouselLabel: '汝塔產品介面',
            carouselInstructions: '左右滑動、拖動，或使用左右方向鍵切換中央顯示的介面。',
            carouselRoleDescription: '輪播圖',
            slideRoleDescription: '介面',
            visuals: [
                {
                    image: 'wisdom',
                    slot: 'start',
                    label: '今日慧語',
                    alt: '汝塔今日慧語介面，展示每日觀照與修學記錄',
                    priority: false,
                },
                {
                    image: 'reading',
                    slot: 'center',
                    label: '經典閱讀',
                    alt: '汝塔經典閱讀介面，展示經文原文、輔助理解工具和聽讀入口',
                    priority: true,
                },
                {
                    image: 'tabao',
                    slot: 'end',
                    label: '塔寶輔助',
                    alt: '汝塔塔寶介面，展示圍繞經典內容的輔助理解與問答',
                    priority: false,
                },
            ],
        },
        why: {
            title: ['經典並不難找。', '難的是理解，', '並持續讀下去。'],
            description: '找到一部經典只是開始。真正的挑戰，是理解原文、建立穩定節奏，並把零散的閱讀、思考與實踐累積為一段可以繼續的個人歷程。',
            mobileDescription: '從閱讀經典、輔助理解，到建立節奏並留下記錄，汝塔讓每一步彼此連接。',
            journeyLabel: '汝塔產品路徑',
            journey: ['閱讀經典', '建立節奏', '沉澱歷程'],
        },
        stories: [
            {
                id: 'reading',
                chapter: '閱讀經典',
                title: ['理解經典，', '從原文開始。'],
                description: '閱讀經典原文；需要時，再查看背景、義理脈絡與術語解釋，讓輔助理解始終回到經文本身。',
                mobileDescription: '閱讀經典原文；需要時，再查看背景、義理與術語解釋，讓輔助理解始終回到經文本身。',
                tone: 'paper',
                visualFirst: true,
                image: 'reading',
                imageAlt: '汝塔經典閱讀介面，展示經文原文、輔助理解工具和聽讀入口',
                caption: '閱讀介面 · 原文與理解工具',
                features: [
                    ['經典原文為本', '先讀原文，再作延伸，保留經文的完整語境。'],
                    ['AI 僅作輔助', '協助梳理背景、概念與上下文，不取代經典原文、傳統注疏或個人判斷。'],
                    ['專注閱讀體驗', '工具只在需要時出現，讓注意力留在經文上。'],
                ],
            },
            {
                id: 'practice',
                chapter: '修學計畫',
                title: ['建立節奏，', '讓長期修學落到每天。'],
                description: '將想長期堅持的閱讀與實踐拆解為清晰計畫，透過目標、進度和每日任務，建立適合自己的修學節奏。',
                mobileDescription: '透過計畫、目標與進度，把長期意願變成今天可以完成的行動。',
                tone: 'mist',
                visualFirst: false,
                image: 'practice',
                imageAlt: '汝塔修學計畫介面，展示今日觀照和修學進度',
                caption: '修學計畫 · 今日觀照',
                features: [
                    ['今日任務清晰', '把閱讀與實踐拆解為今天可以完成的行動。'],
                    ['進度持續可見', '知道已經完成了什麼，也知道下一步從哪裡開始。'],
                    ['路徑由您決定', '工具協助規劃與記錄，不取代個人的修學選擇。'],
                ],
            },
            {
                id: 'history',
                chapter: '個人歷程',
                title: ['記錄每一次閱讀、', '思考與實踐。'],
                description: '保存讀過的內容、當下的思考與持續實踐，把零散片段連接成一段可回望、可繼續的個人修學歷程。',
                mobileDescription: '把零散片段連接成一段可回望、可繼續的個人修學歷程。',
                tone: 'pine',
                visualFirst: true,
                image: 'history',
                imageAlt: '汝塔首頁介面，展示今日觀照、閱讀內容和個人修學記錄',
                caption: '個人歷程 · 閱讀與實踐記錄',
                features: [
                    ['閱讀留下記錄', '每一次進入經典，都成為個人歷程的一部分。'],
                    ['思考逐漸累積', '保存當下的理解，日後回看自己的變化。'],
                    ['計畫連接記錄', '讓今天的行動與長期歷程彼此連接。'],
                ],
            },
        ],
        principles: {
            title: ['技術退後一步，', '讓經典與人', '留在中心。'],
            items: [
                ['尊重傳統', '以經典原文為基礎，尊重傳統文本、注疏與解釋脈絡。'],
                ['AI 僅作輔助', '協助理解內容與語境，不取代經典原文、傳統注疏、個人判斷或老師指導。'],
                ['支持長期探索', '透過閱讀、計畫與記錄，支持穩定而持續的個人修學歷程。'],
            ],
        },
        finalCta: {
            title: '從一段經典開始。',
            mobileTitle: ['從一段經典', '開始。'],
            description: '讓閱讀、理解、計畫與記錄，逐漸連接成一段可以長期繼續的個人歷程。',
        },
        store: {
            sectionLabel: '選擇適合此裝置的下載方式',
            appLanguageNotice: '',
            iosTab: 'iPhone',
            androidTab: 'Android / HarmonyOS',
            actions: {
                open_apple_store: { label: '前往 App Store 下載', description: '前往 App Store 查看並安裝正式版本' },
                open_waitlist: { label: '所在地區開放後通知我', description: '所在地區開放後，我們將透過電子郵件通知您' },
                open_google_play: { label: '前往 Google Play 下載', description: '透過 Google Play 安裝官方版本' },
                open_verified_apk: { label: '下載經校驗的官方 Android 安裝包', description: '核對版本與檔案資訊後下載' },
                expand_testflight: { label: '體驗新版汝塔', description: '內測版，需要完成 2 步' },
                open_testflight_app: { label: '第 1 步 · 安裝 Apple 官方工具', description: '支援 iOS 16 及以上；安裝完成不要點「開啟」，請直接返回本頁面' },
                open_testflight_beta: { label: '第 2 步 · 安裝新版汝塔', description: '返回本頁面點擊這裡，再依提示完成安裝' },
                show_wechat_guide: { label: '在瀏覽器中開啟', description: '微信中無法直接安裝，請先用系統瀏覽器開啟本頁' },
                open_install_documentation: { label: '查看安全安裝方式', description: '查看適合此裝置的官方安裝說明' },
            },
            loading: '正在確認可用的安裝方式…',
            disabled: '目前安裝方式暫不可用，請稍後重試或取得協助',
            waitlistNote: '電子郵件僅用於所在地區的 iOS 開放通知。點擊按鈕後，請完成表單提交；未提交的表單不會登記電子郵件。',
            testflightNote: '看到「輸入兌換碼」？不用填寫。返回瀏覽器，點擊「第 2 步 · 安裝新版汝塔」即可。',
            testflightConfirm: {
                title: '安裝後，請直接返回本頁面',
                description: '這是 Apple 提供的內測安裝工具。安裝完成後不要點「開啟」；若直接開啟後看到「輸入兌換碼」，無需填寫，關閉後回到本頁面即可。',
                cancel: '暫不安裝',
                confirm: '記住了，去安裝',
            },
            wechatGuide: {
                title: '請在系統瀏覽器中開啟',
                description: '點擊微信右上角的選單，再選擇「在瀏覽器中開啟」。返回本頁後，我們會繼續提供適用的安全安裝方式。',
                close: '我知道了',
            },
            help: '需要安裝協助',
        },
        recovery: {
            preparingTitle: '這條連結仍在準備中',
            pausedTitle: '這條連結已暫停使用',
            unavailableTitle: '此連結暫時無法使用',
            description: '無需擔心，您的操作沒有問題。我們不會將您帶到無法使用的商店；您仍可查看官網目前可用的下載方式。',
            primaryAction: '查看可用安裝方式',
            dismiss: '關閉提示並繼續瀏覽官網',
        },
        footer: {
            privacy: '隱私政策',
            terms: '使用協議',
            contact: '聯絡我們',
            help: '幫助中心',
            copyrightOwner: '深圳市师利千秋文化科技有限公司',
            copyrightRights: '保留所有權利。',
            icp: '粤ICP备2025461997号-1',
        },
    },
    en: englishContent,
    ja: japaneseContent,
    ko: koreanContent,
}

export const MARKETING_CONTENT = Object.freeze(content)

export function formatMarketingCopyright(owner, rights, year = new Date().getFullYear()) {
    return `© ${year} ${owner}. ${rights}`
}

export function getMarketingContent(localeKey) {
    const value = MARKETING_CONTENT[localeKey]
    if (!value) throw new Error(`Unsupported marketing locale: ${localeKey}`)
    return value
}
